/*
 * gpubridge_backend_opencl.c — the OpenCL GPU backend.
 *
 * This is the one nontrivial backend in this milestone. Three design
 * decisions shape everything in this file (all explained in depth in
 * CLAUDE.md — this is the short version):
 *
 * 1. NO LINK-TIME DEPENDENCY ON OpenCL. We only #include <CL/cl.h> for its
 *    *type* definitions (cl_int, cl_mem, cl_platform_id, ...) at compile
 *    time. Every actual OpenCL function is resolved at runtime via
 *    dlopen("libOpenCL.so.1") + dlsym(). This means the final executable
 *    has zero ELF NEEDED entry for libOpenCL — verified with
 *    `readelf -d build/gpubridge_vecadd_test | grep NEEDED`. Consequence: this
 *    binary still starts and runs GPUBRIDGE_BACKEND=cpu (or GPUBRIDGE_BACKEND=auto
 *    falling back to CPU) correctly on a machine that has no OpenCL
 *    installed at all — required because the dynamic linker would refuse
 *    to even start a binary that hard-links a missing .so.
 *
 * 2. cl_mem DISGUISED AS void*. The fixed GpuBridgeBackend interface (gpubridge_backend.h)
 *    only has room for plain pointers in malloc_device/copy_to_device/
 *    copy_to_host/launch_vector_add_f32 — there is no separate "device
 *    handle" type. Since cl_mem is itself defined as a pointer
 *    (`typedef struct _cl_mem* cl_mem`), opencl_malloc_device() simply
 *    casts the cl_mem it gets from clCreateBuffer() to void*, and every
 *    other function here casts it straight back. gpubridge_runtime.c and every
 *    other caller never dereference this pointer — they only ever pass it
 *    back into this backend.
 *
 * 3. THE WHOLE REAL IMPLEMENTATION IS #ifdef GPUBRIDGE_HAVE_OPENCL. CMake only
 *    defines GPUBRIDGE_HAVE_OPENCL when it found CL/cl.h on the build machine
 *    (see CMakeLists.txt). When it's not defined, the #else branch below
 *    provides a trivial stub whose available() always returns false, so
 *    this file always compiles regardless of whether the build machine has
 *    OpenCL headers installed — no conditional source-file inclusion
 *    needed in CMakeLists.txt.
 */
#include "gpubridge_backend.h"

#ifdef GPUBRIDGE_HAVE_OPENCL

#include <CL/cl.h>
#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Milestone 3 additions (spec3.md sections 5, 8.5): optional CLBlast GEMM
 * acceleration, and gpuBridgeEnvVendorGemmDisable()/gpuBridgeEnvVerbose() for the
 * dispatch/diagnostics logic below. gpubridge_internal.h's own header comment
 * says it is "not included by any file outside src/" — this file (and
 * gpubridge_opencl_clblast.c) are the documented exception: optional
 * runtime-library integrations, not the original backend-selection plumbing
 * that comment describes (spec3.md section 8.5's note). */
#include "gpubridge_opencl_clblast.h"
#include "gpubridge_internal.h"

/* Generated by CMake at configure time from
 * backends/opencl/vector_add_f32.cl (see CMakeLists.txt's file(READ ... HEX)
 * + configure_file() step and cmake/vector_add_f32_cl.h.in). Defines
 * `static const unsigned char kVectorAddF32Source[]` containing the kernel
 * source as a null-terminated byte array — the single source of truth is
 * the .cl file; nothing here duplicates that text by hand. */
#include "generated/vector_add_f32_cl.h"

/* Milestone 2 additions: same generated-header pattern as
 * vector_add_f32_cl.h above, one per new tensor-op kernel (see
 * CMakeLists.txt's GPUBRIDGE_TENSOR_KERNELS loop and cmake/*_cl.h.in). */
#include "generated/matmul_f32_cl.h"
#include "generated/reduce_sum_f32_cl.h"
#include "generated/broadcast_add_f32_cl.h"
#include "generated/relu_f32_cl.h"

/*
 * Function-pointer typedefs mirroring the CL/cl.h prototypes we need.
 * These exist purely so dlsym()'s untyped `void*` result can be stored in a
 * correctly-typed variable and called normally (g.clFoo(...) instead of a
 * cast at every call site). Each one must match the real OpenCL prototype
 * exactly, or calls through it are undefined behavior — cl.h's own
 * declarations are the authority; keep these in sync if the set of calls
 * used below ever changes.
 */
typedef cl_int (*PFN_clGetPlatformIDs)(cl_uint, cl_platform_id*, cl_uint*);
typedef cl_int (*PFN_clGetDeviceIDs)(cl_platform_id, cl_device_type, cl_uint,
    cl_device_id*, cl_uint*);
/* Milestone 3 (spec3.md section 8.5): device-name reporting for the
 * benchmark's diagnostics only — not used by any probe/init/launch path. */
typedef cl_int (*PFN_clGetDeviceInfo)(cl_device_id, cl_device_info, size_t,
    void*, size_t*);
typedef cl_context (*PFN_clCreateContext)(const cl_context_properties*,
    cl_uint, const cl_device_id*,
    void (*)(const char*, const void*, size_t, void*), void*, cl_int*);
typedef cl_command_queue (*PFN_clCreateCommandQueue)(cl_context, cl_device_id,
    cl_command_queue_properties, cl_int*);
typedef cl_mem (*PFN_clCreateBuffer)(cl_context, cl_mem_flags, size_t, void*,
    cl_int*);
typedef cl_int (*PFN_clEnqueueWriteBuffer)(cl_command_queue, cl_mem, cl_bool,
    size_t, size_t, const void*, cl_uint, const cl_event*, cl_event*);
typedef cl_int (*PFN_clEnqueueReadBuffer)(cl_command_queue, cl_mem, cl_bool,
    size_t, size_t, void*, cl_uint, const cl_event*, cl_event*);
typedef cl_program (*PFN_clCreateProgramWithSource)(cl_context, cl_uint,
    const char**, const size_t*, cl_int*);
typedef cl_int (*PFN_clBuildProgram)(cl_program, cl_uint, const cl_device_id*,
    const char*, void (*)(cl_program, void*), void*);
typedef cl_int (*PFN_clGetProgramBuildInfo)(cl_program, cl_device_id,
    cl_program_build_info, size_t, void*, size_t*);
typedef cl_kernel (*PFN_clCreateKernel)(cl_program, const char*, cl_int*);
typedef cl_int (*PFN_clSetKernelArg)(cl_kernel, cl_uint, size_t, const void*);
typedef cl_int (*PFN_clEnqueueNDRangeKernel)(cl_command_queue, cl_kernel,
    cl_uint, const size_t*, const size_t*, const size_t*, cl_uint,
    const cl_event*, cl_event*);
typedef cl_int (*PFN_clFinish)(cl_command_queue);
typedef cl_int (*PFN_clReleaseMemObject)(cl_mem);
typedef cl_int (*PFN_clReleaseKernel)(cl_kernel);
typedef cl_int (*PFN_clReleaseProgram)(cl_program);
typedef cl_int (*PFN_clReleaseCommandQueue)(cl_command_queue);
typedef cl_int (*PFN_clReleaseContext)(cl_context);

/*
 * All of this backend's mutable state lives in one anonymous-struct global
 * `g`, deliberately zero-initialized by static storage duration rules (no
 * explicit initializer needed): dlopen handle, resolved function pointers,
 * cached availability-probe result, the live OpenCL objects
 * (platform/device/context/queue/program/kernel), and the last-error
 * buffer. There is exactly one OpenCL backend instance in this process, so
 * a single global struct (rather than a heap-allocated context object) is
 * the simplest correct choice here.
 */
static struct {
    void* dl_handle;
    bool probed;
    bool probe_result;

    PFN_clGetPlatformIDs clGetPlatformIDs;
    PFN_clGetDeviceIDs clGetDeviceIDs;
    PFN_clGetDeviceInfo clGetDeviceInfo;
    PFN_clCreateContext clCreateContext;
    PFN_clCreateCommandQueue clCreateCommandQueue;
    PFN_clCreateBuffer clCreateBuffer;
    PFN_clEnqueueWriteBuffer clEnqueueWriteBuffer;
    PFN_clEnqueueReadBuffer clEnqueueReadBuffer;
    PFN_clCreateProgramWithSource clCreateProgramWithSource;
    PFN_clBuildProgram clBuildProgram;
    PFN_clGetProgramBuildInfo clGetProgramBuildInfo;
    PFN_clCreateKernel clCreateKernel;
    PFN_clSetKernelArg clSetKernelArg;
    PFN_clEnqueueNDRangeKernel clEnqueueNDRangeKernel;
    PFN_clFinish clFinish;
    PFN_clReleaseMemObject clReleaseMemObject;
    PFN_clReleaseKernel clReleaseKernel;
    PFN_clReleaseProgram clReleaseProgram;
    PFN_clReleaseCommandQueue clReleaseCommandQueue;
    PFN_clReleaseContext clReleaseContext;

    cl_platform_id platform;
    cl_device_id device;
    cl_context context;
    cl_command_queue queue;
    cl_program program;
    cl_kernel kernel;

    /* Milestone 2 additions: one program+kernel pair per new tensor op,
     * built in opencl_init() alongside the vector_add_f32 program/kernel
     * above. Kept as separate cl_program objects (rather than one program
     * with five kernels) so each kernel's build failure is attributable to
     * its own source file, matching the one-kernel-per-.cl-file layout on
     * disk. */
    cl_program matmul_program;
    cl_kernel matmul_kernel;
    cl_program reduce_sum_program;
    cl_kernel reduce_sum_kernel;
    cl_program broadcast_add_program;
    cl_kernel broadcast_add_kernel;
    cl_program relu_program;
    cl_kernel relu_kernel;

    char last_error[256];
} g;

/* Records `msg` as the reason for the most recent failure; retrieved later
 * via opencl_last_error() / the GpuBridgeBackend.last_error vtable slot. */
static void set_error(const char* msg)
{
    snprintf(g.last_error, sizeof(g.last_error), "%s", msg);
}

/*
 * Maps the handful of OpenCL error codes we're most likely to actually hit
 * in this milestone to readable names, with a numeric fallback for
 * anything else. Deliberately not an exhaustive table — this is a
 * milestone-0 prototype, not a production error-code mapping layer; the
 * numeric fallback keeps every code at least minimally diagnosable.
 */
static const char* cl_error_to_string(cl_int err)
{
    switch (err) {
    case CL_SUCCESS: return "CL_SUCCESS";
    case CL_DEVICE_NOT_FOUND: return "CL_DEVICE_NOT_FOUND";
    case CL_DEVICE_NOT_AVAILABLE: return "CL_DEVICE_NOT_AVAILABLE";
    case CL_OUT_OF_RESOURCES: return "CL_OUT_OF_RESOURCES";
    case CL_OUT_OF_HOST_MEMORY: return "CL_OUT_OF_HOST_MEMORY";
    case CL_BUILD_PROGRAM_FAILURE: return "CL_BUILD_PROGRAM_FAILURE";
    case CL_INVALID_VALUE: return "CL_INVALID_VALUE";
    case CL_INVALID_CONTEXT: return "CL_INVALID_CONTEXT";
    case CL_INVALID_KERNEL_ARGS: return "CL_INVALID_KERNEL_ARGS";
    case CL_MEM_OBJECT_ALLOCATION_FAILURE:
        return "CL_MEM_OBJECT_ALLOCATION_FAILURE";
    default: {
        /* static: safe to return from a function (outlives the call), at
         * the cost of not being thread-safe/reentrant-safe — acceptable
         * for this single-threaded milestone. */
        static char buf[64];
        snprintf(buf, sizeof(buf), "OpenCL error %d", (int)err);
        return buf;
    }
    }
}

/*
 * Opens the OpenCL ICD loader shared library, if not already open.
 * Tries the versioned SONAME first (libOpenCL.so.1, what's actually
 * installed at runtime on a normal system), falling back to the unversioned
 * dev-symlink name (libOpenCL.so) in case only that's present. Idempotent:
 * safe to call repeatedly; only actually dlopen()s once.
 */
static bool dl_open_loader(void)
{
    if (g.dl_handle != NULL) {
        return true;
    }
    g.dl_handle = dlopen("libOpenCL.so.1", RTLD_NOW);
    if (g.dl_handle == NULL) {
        g.dl_handle = dlopen("libOpenCL.so", RTLD_NOW);
    }
    return g.dl_handle != NULL;
}

/* Resolves symbol `fn` from the already-open loader into g.fn, recording an
 * error and returning false (from the enclosing function) if the symbol
 * can't be found. Used instead of repeating this four-line pattern by hand
 * for each of the ~17 entry points below. */
#define DLSYM_OR_FAIL(fn) \
    do { \
        g.fn = (PFN_##fn)dlsym(g.dl_handle, #fn); \
        if (g.fn == NULL) { \
            set_error("failed to resolve " #fn " from libOpenCL"); \
            return false; \
        } \
    } while (0)

/* The minimal set of symbols needed just to *probe* whether a usable GPU
 * exists (clGetPlatformIDs/clGetDeviceIDs) — kept separate from
 * resolve_all_symbols() so opencl_available() can stay cheap and does not
 * need to resolve context/queue/kernel-related symbols it will never use
 * if this backend ends up not being selected. */
static bool resolve_probe_symbols(void)
{
    DLSYM_OR_FAIL(clGetPlatformIDs);
    DLSYM_OR_FAIL(clGetDeviceIDs);
    return true;
}

/* Resolves every OpenCL entry point this backend uses, called once from
 * opencl_init() after this backend has actually been selected. */
static bool resolve_all_symbols(void)
{
    if (!resolve_probe_symbols()) {
        return false;
    }
    /* Milestone 3 (spec3.md section 8.5): only used by
     * gpuBridgeOpenclGetDeviceName(), never by any probe/init/launch path
     * above — resolved here anyway since resolve_all_symbols() is where
     * everything this backend might need is already collected. */
    DLSYM_OR_FAIL(clGetDeviceInfo);
    DLSYM_OR_FAIL(clCreateContext);
    DLSYM_OR_FAIL(clCreateCommandQueue);
    DLSYM_OR_FAIL(clCreateBuffer);
    DLSYM_OR_FAIL(clEnqueueWriteBuffer);
    DLSYM_OR_FAIL(clEnqueueReadBuffer);
    DLSYM_OR_FAIL(clCreateProgramWithSource);
    DLSYM_OR_FAIL(clBuildProgram);
    DLSYM_OR_FAIL(clGetProgramBuildInfo);
    DLSYM_OR_FAIL(clCreateKernel);
    DLSYM_OR_FAIL(clSetKernelArg);
    DLSYM_OR_FAIL(clEnqueueNDRangeKernel);
    DLSYM_OR_FAIL(clFinish);
    DLSYM_OR_FAIL(clReleaseMemObject);
    DLSYM_OR_FAIL(clReleaseKernel);
    DLSYM_OR_FAIL(clReleaseProgram);
    DLSYM_OR_FAIL(clReleaseCommandQueue);
    DLSYM_OR_FAIL(clReleaseContext);
    return true;
}

/*
 * Searches every OpenCL platform for the first GPU-type device and returns
 * it via out_platform/out_device. Requires g.clGetPlatformIDs/
 * g.clGetDeviceIDs to already be resolved (i.e. resolve_probe_symbols() has
 * succeeded). Returns false if no platform has any CL_DEVICE_TYPE_GPU
 * device (e.g. OpenCL is installed but only exposes a CPU device, or
 * nothing at all).
 */
static bool find_gpu_device(cl_platform_id* out_platform,
                             cl_device_id* out_device)
{
    cl_uint num_platforms = 0;
    if (g.clGetPlatformIDs(0, NULL, &num_platforms) != CL_SUCCESS ||
        num_platforms == 0) {
        return false;
    }

    cl_platform_id* platforms =
        malloc(sizeof(cl_platform_id) * num_platforms);
    if (platforms == NULL) {
        return false;
    }
    g.clGetPlatformIDs(num_platforms, platforms, NULL);

    bool found = false;
    for (cl_uint i = 0; i < num_platforms && !found; i++) {
        cl_uint num_devices = 0;
        /* First call: just ask how many GPU devices this platform has
         * (num_devices), without fetching any IDs yet. */
        if (g.clGetDeviceIDs(platforms[i], CL_DEVICE_TYPE_GPU, 0, NULL,
                &num_devices) == CL_SUCCESS && num_devices > 0) {
            cl_device_id device;
            /* Second call: this milestone only needs a single device, so
             * just fetch the first GPU device on this platform. */
            if (g.clGetDeviceIDs(platforms[i], CL_DEVICE_TYPE_GPU, 1,
                    &device, NULL) == CL_SUCCESS) {
                *out_platform = platforms[i];
                *out_device = device;
                found = true;
            }
        }
    }

    free(platforms);
    return found;
}

static bool opencl_available(void)
{
    /* Cache the result: available() must be cheap to call repeatedly
     * (gpubridge_selector.c calls it on every gpuBridgeInit()/gpuBridgeSetBackend(), and
     * diagnostics need to know OpenCL's availability even when CPU was the
     * one actually selected). The first call does the real dlopen+probe
     * work; every call after that just returns the cached result. */
    if (g.probed) {
        return g.probe_result;
    }
    g.probed = true;
    g.probe_result = false;

    if (!dl_open_loader()) {
        /* No libOpenCL.so[.1] found on this system at all — OpenCL is
         * simply not installed. Not an error, just "unavailable". */
        return false;
    }
    if (!resolve_probe_symbols()) {
        return false;
    }

    cl_platform_id platform;
    cl_device_id device;
    g.probe_result = find_gpu_device(&platform, &device);
    return g.probe_result;
}

/*
 * Milestone 2 addition: compiles `source` (a null-terminated kernel source
 * string, from one of the generated/*.h headers) into a cl_program and
 * extracts the `kernel_name` kernel from it. Factors out the
 * clCreateProgramWithSource -> clBuildProgram -> clCreateKernel sequence
 * that opencl_init()'s existing vector_add_f32 setup already does inline
 * (left untouched below, for regression safety) so it isn't repeated four
 * more times by hand for the new tensor-op kernels. On build failure,
 * surfaces the compiler's build log exactly like the inline vector_add_f32
 * path does.
 */
static bool build_program_kernel(const char* source, const char* kernel_name,
    cl_program* out_program, cl_kernel* out_kernel)
{
    cl_int err;
    size_t src_len = strlen(source);
    cl_program program = g.clCreateProgramWithSource(g.context, 1, &source,
        &src_len, &err);
    if (program == NULL) {
        set_error(cl_error_to_string(err));
        return false;
    }

    err = g.clBuildProgram(program, 1, &g.device, NULL, NULL, NULL);
    if (err != CL_SUCCESS) {
        char log[2048];
        size_t log_len = 0;
        g.clGetProgramBuildInfo(program, g.device, CL_PROGRAM_BUILD_LOG,
            sizeof(log) - 1, log, &log_len);
        log[log_len < sizeof(log) ? log_len : sizeof(log) - 1] = '\0';
        char full[sizeof(g.last_error)];
        snprintf(full, sizeof(full), "OpenCL build failure (%s): %s",
            kernel_name, log);
        set_error(full);
        return false;
    }

    cl_kernel kernel = g.clCreateKernel(program, kernel_name, &err);
    if (kernel == NULL) {
        set_error(cl_error_to_string(err));
        return false;
    }

    *out_program = program;
    *out_kernel = kernel;
    return true;
}

static bool opencl_init(void)
{
    /* Re-run (or reuse the cached result of) the availability probe first
     * — init() must not be called before available() has returned true,
     * but guard here defensively anyway. */
    if (!opencl_available()) {
        set_error("no OpenCL GPU device available");
        return false;
    }

    if (!resolve_all_symbols()) {
        return false;
    }

    /* Re-find the device rather than reusing whatever opencl_available()
     * found: cl_platform_id/cl_device_id handles are cheap to re-query and
     * this keeps opencl_available() free of any side effects on g.platform/
     * g.device (it only ever touches g.probed/g.probe_result). */
    if (!find_gpu_device(&g.platform, &g.device)) {
        set_error("no OpenCL GPU device available");
        return false;
    }

    cl_int err;
    /* One context, one device, no notification callback — the minimum
     * needed for a single-device, single-queue milestone-0 prototype. */
    g.context = g.clCreateContext(NULL, 1, &g.device, NULL, NULL, &err);
    if (g.context == NULL) {
        set_error(cl_error_to_string(err));
        return false;
    }

    /* clCreateCommandQueue (not the newer clCreateCommandQueueWithProperties)
     * is deprecated in OpenCL 2.0+ but universally supported, including by
     * the NVIDIA driver on this machine; using it avoids the properties-
     * array boilerplate the newer API requires, which isn't worth it for a
     * single synchronous queue in this prototype. properties=0 means no
     * special queue behavior (no out-of-order execution, no profiling). */
    g.queue = g.clCreateCommandQueue(g.context, g.device, 0, &err);
    if (g.queue == NULL) {
        set_error(cl_error_to_string(err));
        return false;
    }

    /* kVectorAddF32Source (from the CMake-generated header) is a
     * null-terminated byte array holding the exact text of
     * vector_add_f32.cl; strlen() gives clCreateProgramWithSource the
     * source length it needs. */
    const char* src = (const char*)kVectorAddF32Source;
    size_t src_len = strlen(src);
    g.program = g.clCreateProgramWithSource(g.context, 1, &src, &src_len,
        &err);
    if (g.program == NULL) {
        set_error(cl_error_to_string(err));
        return false;
    }

    /* Compile the kernel source for our one device. NULL options string:
     * no special compiler flags needed for this simple kernel. */
    err = g.clBuildProgram(g.program, 1, &g.device, NULL, NULL, NULL);
    if (err != CL_SUCCESS) {
        /* A build failure is the single most likely OpenCL error to hit
         * during development, and by far the most useful thing to report is
         * the compiler's own build log — so fetch and surface it rather
         * than just the generic CL_BUILD_PROGRAM_FAILURE code. */
        char log[2048];
        size_t log_len = 0;
        g.clGetProgramBuildInfo(g.program, g.device, CL_PROGRAM_BUILD_LOG,
            sizeof(log) - 1, log, &log_len);
        log[log_len < sizeof(log) ? log_len : sizeof(log) - 1] = '\0';
        char full[sizeof(g.last_error)];
        snprintf(full, sizeof(full), "OpenCL build failure: %s", log);
        set_error(full);
        return false;
    }

    /* "vector_add_f32" must exactly match the __kernel function name in
     * vector_add_f32.cl. */
    g.kernel = g.clCreateKernel(g.program, "vector_add_f32", &err);
    if (g.kernel == NULL) {
        set_error(cl_error_to_string(err));
        return false;
    }

    /* Milestone 2: build the four new tensor-op kernels the same way, using
     * build_program_kernel() instead of vector_add_f32's inline sequence
     * above. Any one build failure aborts init() with a specific,
     * per-kernel error message (build_program_kernel sets it). */
    if (!build_program_kernel((const char*)kMatmulF32Source, "matmul_f32",
            &g.matmul_program, &g.matmul_kernel)) {
        return false;
    }
    if (!build_program_kernel((const char*)kReduceSumF32Source,
            "reduce_sum_f32", &g.reduce_sum_program,
            &g.reduce_sum_kernel)) {
        return false;
    }
    if (!build_program_kernel((const char*)kBroadcastAddF32Source,
            "broadcast_add_f32", &g.broadcast_add_program,
            &g.broadcast_add_kernel)) {
        return false;
    }
    if (!build_program_kernel((const char*)kReluF32Source, "relu_f32",
            &g.relu_program, &g.relu_kernel)) {
        return false;
    }

    /* Milestone 3 (spec3.md section 5.2): optional CLBlast probe, after the
     * guaranteed hand-written matmul kernel is already built and ready —
     * a CLBlast probe failure or absence never blocks it. Result
     * intentionally ignored: CLBlast is acceleration, not a requirement,
     * so it must never cause opencl_init() itself to fail. */
    gpuBridgeOpenclClblastTryInit();

    return true;
}

static void opencl_shutdown(void)
{
    /* Release in reverse order of creation (kernel -> program -> queue ->
     * context), null out each handle afterward so a stray second call to
     * shutdown() (or a call after a partially-failed init()) is safe —
     * every release is guarded by "was this ever created". Note: the
     * platform/device IDs themselves aren't OpenCL objects we created (the
     * ICD owns them), so there's nothing to release for those. */
    if (g.relu_kernel) { g.clReleaseKernel(g.relu_kernel); g.relu_kernel = NULL; }
    if (g.relu_program) { g.clReleaseProgram(g.relu_program); g.relu_program = NULL; }
    if (g.broadcast_add_kernel) { g.clReleaseKernel(g.broadcast_add_kernel); g.broadcast_add_kernel = NULL; }
    if (g.broadcast_add_program) { g.clReleaseProgram(g.broadcast_add_program); g.broadcast_add_program = NULL; }
    if (g.reduce_sum_kernel) { g.clReleaseKernel(g.reduce_sum_kernel); g.reduce_sum_kernel = NULL; }
    if (g.reduce_sum_program) { g.clReleaseProgram(g.reduce_sum_program); g.reduce_sum_program = NULL; }
    if (g.matmul_kernel) { g.clReleaseKernel(g.matmul_kernel); g.matmul_kernel = NULL; }
    if (g.matmul_program) { g.clReleaseProgram(g.matmul_program); g.matmul_program = NULL; }
    if (g.kernel) { g.clReleaseKernel(g.kernel); g.kernel = NULL; }
    if (g.program) { g.clReleaseProgram(g.program); g.program = NULL; }
    if (g.queue) { g.clReleaseCommandQueue(g.queue); g.queue = NULL; }
    if (g.context) { g.clReleaseContext(g.context); g.context = NULL; }
}

static void* opencl_malloc_device(size_t bytes)
{
    /* CL_MEM_READ_WRITE: this milestone doesn't distinguish read-only vs.
     * write-only buffers at the allocation level (unlike the GpuBridgeBufferArg
     * is_input/is_output flags in gpubridge_ir.h, which are descriptive metadata
     * only, not enforced by the backend). NULL host_ptr: we're not wrapping
     * existing host memory, this is a fresh device-only allocation. */
    cl_int err;
    cl_mem buf = g.clCreateBuffer(g.context, CL_MEM_READ_WRITE, bytes, NULL,
        &err);
    if (buf == NULL) {
        set_error(cl_error_to_string(err));
        return NULL;
    }
    /* See the file header comment: cl_mem is already pointer-shaped, so
     * this cast is how an OpenCL buffer handle travels through the
     * GpuBridgeBackend interface's plain void* return type. */
    return (void*)buf;
}

static void opencl_free_device(void* ptr)
{
    if (ptr != NULL) {
        g.clReleaseMemObject((cl_mem)ptr);
    }
}

static bool opencl_copy_to_device(void* dst, const void* src, size_t bytes)
{
    /* CL_TRUE = blocking write: does not return until the copy has actually
     * completed, so gpubridge_runtime.c's gpuBridgeMemcpy() never needs a separate sync
     * call for correctness. dst is a cl_mem handle (from
     * opencl_malloc_device), cast back from the void* it travels as. */
    cl_int err = g.clEnqueueWriteBuffer(g.queue, (cl_mem)dst, CL_TRUE, 0,
        bytes, src, 0, NULL, NULL);
    if (err != CL_SUCCESS) {
        set_error(cl_error_to_string(err));
        return false;
    }
    return true;
}

static bool opencl_copy_to_host(void* dst, const void* src, size_t bytes)
{
    /* Mirror image of copy_to_device: src is the cl_mem handle here,
     * blocking read (CL_TRUE) for the same reason. */
    cl_int err = g.clEnqueueReadBuffer(g.queue, (cl_mem)src, CL_TRUE, 0,
        bytes, dst, 0, NULL, NULL);
    if (err != CL_SUCCESS) {
        set_error(cl_error_to_string(err));
        return false;
    }
    return true;
}

static bool opencl_launch_vector_add_f32(
    const float* a, const float* b, float* c, size_t n)
{
    /* a/b/c arrive typed as (const) float pointers only because that's the
     * fixed GpuBridgeBackend signature; they are actually cl_mem handles that were
     * merely disguised as pointers by opencl_malloc_device(). Cast back
     * before use — never dereferenced as real float pointers. */
    cl_mem mem_a = (cl_mem)(void*)a;
    cl_mem mem_b = (cl_mem)(void*)b;
    cl_mem mem_c = (cl_mem)(void*)c;
    cl_int n_arg = (cl_int)n;

    /* Bind the four kernel arguments in the exact order they appear in
     * vector_add_f32.cl's parameter list (a, b, c, n). Short-circuits on
     * the first failure via the `err == CL_SUCCESS` chain rather than
     * checking and reporting each clSetKernelArg call separately. */
    cl_int err;
    err = g.clSetKernelArg(g.kernel, 0, sizeof(cl_mem), &mem_a);
    if (err == CL_SUCCESS) {
        err = g.clSetKernelArg(g.kernel, 1, sizeof(cl_mem), &mem_b);
    }
    if (err == CL_SUCCESS) {
        err = g.clSetKernelArg(g.kernel, 2, sizeof(cl_mem), &mem_c);
    }
    if (err == CL_SUCCESS) {
        err = g.clSetKernelArg(g.kernel, 3, sizeof(cl_int), &n_arg);
    }
    if (err != CL_SUCCESS) {
        set_error(cl_error_to_string(err));
        return false;
    }

    /* One work-item per output element, matching the kernel's
     * get_global_id(0) indexing. NULL local work-group size: let the OpenCL
     * driver pick one — this milestone doesn't need manual tuning, and n is
     * not required to be a multiple of any particular work-group size. This
     * call only enqueues the kernel; it does not block (see opencl_sync()
     * for that). */
    size_t global_size = n;
    err = g.clEnqueueNDRangeKernel(g.queue, g.kernel, 1, NULL, &global_size,
        NULL, 0, NULL, NULL);
    if (err != CL_SUCCESS) {
        set_error(cl_error_to_string(err));
        return false;
    }
    return true;
}

static bool opencl_sync(void)
{
    /* Blocks until every previously enqueued command on this queue
     * (writes, the kernel launch, reads) has completed. */
    cl_int err = g.clFinish(g.queue);
    if (err != CL_SUCCESS) {
        set_error(cl_error_to_string(err));
        return false;
    }
    return true;
}

static const char* opencl_last_error(void)
{
    return g.last_error;
}

/* --- Milestone 1.5 addition (spec1.5.md section 12) ---
 *
 * Honest reporting of this file's *current* behavior, not a hardware
 * capability probe:
 *   - supports_device_local_memory = true: clCreateBuffer() above allocates
 *     real device memory on a discrete GPU (spec1.5.md section 12).
 *   - supports_async_kernel_launch = true: clEnqueueNDRangeKernel() (see
 *     opencl_launch_vector_add_f32 and the tensor-op launch functions below)
 *     does not block; completion is only observed later via clFinish() in
 *     opencl_sync().
 *   - supports_shared_memory = false: no SVM/USM allocation path exists.
 *   - supports_host_pinned_memory = false: CL_MEM_ALLOC_HOST_PTR is never
 *     used by opencl_malloc_device().
 *   - supports_async_copy = false: opencl_copy_to_device/opencl_copy_to_host
 *     use blocking CL_TRUE for clEnqueueWriteBuffer/clEnqueueReadBuffer.
 *   - supports_events = false: no clEnqueue* call anywhere in this file
 *     passes a non-NULL cl_event* out-param.
 *   - supports_profiling_timestamps = false: the command queue above is
 *     created with properties=0, i.e. without CL_QUEUE_PROFILING_ENABLE.
 */
static bool opencl_get_caps(GpuBridgeBackendCaps* out_caps)
{
    *out_caps = (GpuBridgeBackendCaps){
        .supports_device_local_memory = true,
        .supports_async_kernel_launch = true,
        /* Milestone 3 (spec3.md section 8.2): honest "loaded" reporting,
         * not "enabled" (that also depends on GPUBRIDGE_VENDOR_GEMM_DISABLE)
         * or "used" (only knowable per-launch). */
        .vendor_gemm_loaded = gpuBridgeOpenclClblastAvailable(),
    };
    return true;
}

/* --- Milestone 3 addition (spec3.md section 8.5) ---
 * Device identity — a property of this backend itself, independent of
 * whether CLBlast happens to be loaded, so it lives here rather than in
 * gpubridge_opencl_clblast.c. */
bool gpuBridgeOpenclGetDeviceName(char* buf, size_t buf_len)
{
    if (g.device == NULL || g.clGetDeviceInfo == NULL) {
        snprintf(buf, buf_len, "unknown");
        return false;
    }
    if (g.clGetDeviceInfo(g.device, CL_DEVICE_NAME, buf_len, buf, NULL) != CL_SUCCESS) {
        snprintf(buf, buf_len, "unknown");
        return false;
    }
    return true;
}

/* --- Phase 4 addition (spec4.md section 9.1) --- */
bool gpuBridgeOpenclGetDeviceMemoryLimit(size_t* out_bytes)
{
    *out_bytes = 0;
    if (g.device == NULL || g.clGetDeviceInfo == NULL) {
        return false;
    }
    cl_ulong mem_size = 0;
    if (g.clGetDeviceInfo(g.device, CL_DEVICE_GLOBAL_MEM_SIZE, sizeof(mem_size),
            &mem_size, NULL) != CL_SUCCESS) {
        return false;
    }
    *out_bytes = (size_t)mem_size;
    return true;
}

/* --- Milestone 2 additions (spec2.md section 7): OpenCL launch functions
 * for the four new tensor ops. Same disguised-cl_mem-as-void-pointer and
 * blocking-write conventions as opencl_launch_vector_add_f32 above — see that function's
 * comment and the file header for why. */

static bool opencl_launch_matmul_f32(
    const float* a, const float* b, float* c, size_t m, size_t k, size_t n)
{
    if (gpuBridgeEnvVerbose()) {
        printf("we are in function: opencl_launch_matmul_f32\n"
            "purpose: dispatch matmul_f32 (C[%zu,%zu] = A[%zu,%zu] x B[%zu,%zu]) "
            "on the OpenCL backend — tries CLBlast's tuned GEMM first, falls "
            "back to GPUBridge's own hand-written matmul_f32.cl kernel\n",
            m, n, m, k, k, n);
    }

    /* Milestone 3 (spec3.md section 5.2): try the optional CLBlast fast
     * path first. Two failure modes handled deliberately differently:
     * CLBlast never loading is not an error (falls through silently to
     * the hand-written kernel below, exactly like OpenCL itself not being
     * installed silently falls back to CPU); CLBlast loading but the call
     * itself failing is a genuine fault — reported via set_error(), never
     * masked by a silent fallback (gpubridge_performance_spec.md section
     * 3.10: "must never silently fail into a slow or incorrect path"). */
    if (gpuBridgeOpenclClblastAvailable() && !gpuBridgeEnvVendorGemmDisable()) {
        char err_buf[128];
        if (gpuBridgeOpenclClblastSgemmF32(g.queue, (cl_mem)(void*)a,
                (cl_mem)(void*)b, (cl_mem)(void*)c, m, k, n, err_buf, sizeof(err_buf))) {
            if (gpuBridgeEnvVerbose()) {
                printf("leaving function: opencl_launch_matmul_f32, "
                    "result: success (path=clblast)\n\n");
            }
            return true;
        }
        if (gpuBridgeEnvVerbose()) {
            printf("  gemm result: failed (%s)\n", err_buf);
            printf("leaving function: opencl_launch_matmul_f32, "
                "result: failed (path=clblast, %s)\n\n", err_buf);
        }
        set_error(err_buf);
        return false;
    }

    cl_mem mem_a = (cl_mem)(void*)a;
    cl_mem mem_b = (cl_mem)(void*)b;
    cl_mem mem_c = (cl_mem)(void*)c;
    cl_int m_arg = (cl_int)m;
    cl_int k_arg = (cl_int)k;
    cl_int n_arg = (cl_int)n;

    cl_int err;
    err = g.clSetKernelArg(g.matmul_kernel, 0, sizeof(cl_mem), &mem_a);
    if (err == CL_SUCCESS) {
        err = g.clSetKernelArg(g.matmul_kernel, 1, sizeof(cl_mem), &mem_b);
    }
    if (err == CL_SUCCESS) {
        err = g.clSetKernelArg(g.matmul_kernel, 2, sizeof(cl_mem), &mem_c);
    }
    if (err == CL_SUCCESS) {
        err = g.clSetKernelArg(g.matmul_kernel, 3, sizeof(cl_int), &m_arg);
    }
    if (err == CL_SUCCESS) {
        err = g.clSetKernelArg(g.matmul_kernel, 4, sizeof(cl_int), &k_arg);
    }
    if (err == CL_SUCCESS) {
        err = g.clSetKernelArg(g.matmul_kernel, 5, sizeof(cl_int), &n_arg);
    }
    if (err != CL_SUCCESS) {
        set_error(cl_error_to_string(err));
        if (gpuBridgeEnvVerbose()) {
            printf("leaving function: opencl_launch_matmul_f32, "
                "result: failed (path=naive_kernel, clSetKernelArg: %s)\n\n",
                cl_error_to_string(err));
        }
        return false;
    }

    /* One work-item per output element C[row,col] — 2D global size (m, n),
     * matching matmul_f32.cl's get_global_id(0)/get_global_id(1) indexing
     * (spec2.md 7.1). */
    size_t global_size[2] = { m, n };
    err = g.clEnqueueNDRangeKernel(g.queue, g.matmul_kernel, 2, NULL,
        global_size, NULL, 0, NULL, NULL);
    if (err != CL_SUCCESS) {
        set_error(cl_error_to_string(err));
        if (gpuBridgeEnvVerbose()) {
            printf("leaving function: opencl_launch_matmul_f32, "
                "result: failed (path=naive_kernel, clEnqueueNDRangeKernel: %s)\n\n",
                cl_error_to_string(err));
        }
        return false;
    }
    if (gpuBridgeEnvVerbose()) {
        printf("leaving function: opencl_launch_matmul_f32, "
            "result: success (path=naive_kernel)\n\n");
    }
    return true;
}

static bool opencl_launch_reduce_sum_f32(
    const float* a, float* result, size_t n)
{
    cl_mem mem_a = (cl_mem)(void*)a;
    cl_mem mem_result = (cl_mem)(void*)result;
    cl_int n_arg = (cl_int)n;

    cl_int err;
    err = g.clSetKernelArg(g.reduce_sum_kernel, 0, sizeof(cl_mem), &mem_a);
    if (err == CL_SUCCESS) {
        err = g.clSetKernelArg(g.reduce_sum_kernel, 1, sizeof(cl_mem),
            &mem_result);
    }
    if (err == CL_SUCCESS) {
        err = g.clSetKernelArg(g.reduce_sum_kernel, 2, sizeof(cl_int),
            &n_arg);
    }
    if (err != CL_SUCCESS) {
        set_error(cl_error_to_string(err));
        return false;
    }

    /* Naive single-work-group sequential accumulation (spec2.md 7.2): one
     * work-item total, which itself walks the whole array. */
    size_t global_size = 1;
    err = g.clEnqueueNDRangeKernel(g.queue, g.reduce_sum_kernel, 1, NULL,
        &global_size, NULL, 0, NULL, NULL);
    if (err != CL_SUCCESS) {
        set_error(cl_error_to_string(err));
        return false;
    }
    return true;
}

static bool opencl_launch_broadcast_add_f32(
    float* y, const float* bias, size_t rows, size_t cols)
{
    cl_mem mem_y = (cl_mem)(void*)y;
    cl_mem mem_bias = (cl_mem)(void*)bias;
    cl_int rows_arg = (cl_int)rows;
    cl_int cols_arg = (cl_int)cols;

    cl_int err;
    err = g.clSetKernelArg(g.broadcast_add_kernel, 0, sizeof(cl_mem),
        &mem_y);
    if (err == CL_SUCCESS) {
        err = g.clSetKernelArg(g.broadcast_add_kernel, 1, sizeof(cl_mem),
            &mem_bias);
    }
    if (err == CL_SUCCESS) {
        err = g.clSetKernelArg(g.broadcast_add_kernel, 2, sizeof(cl_int),
            &rows_arg);
    }
    if (err == CL_SUCCESS) {
        err = g.clSetKernelArg(g.broadcast_add_kernel, 3, sizeof(cl_int),
            &cols_arg);
    }
    if (err != CL_SUCCESS) {
        set_error(cl_error_to_string(err));
        return false;
    }

    /* One work-item per output element, 2D global size (rows, cols)
     * (spec2.md 7.3). */
    size_t global_size[2] = { rows, cols };
    err = g.clEnqueueNDRangeKernel(g.queue, g.broadcast_add_kernel, 2, NULL,
        global_size, NULL, 0, NULL, NULL);
    if (err != CL_SUCCESS) {
        set_error(cl_error_to_string(err));
        return false;
    }
    return true;
}

static bool opencl_launch_relu_f32(const float* x, float* y, size_t count)
{
    cl_mem mem_x = (cl_mem)(void*)x;
    cl_mem mem_y = (cl_mem)(void*)y;
    cl_int count_arg = (cl_int)count;

    cl_int err;
    err = g.clSetKernelArg(g.relu_kernel, 0, sizeof(cl_mem), &mem_x);
    if (err == CL_SUCCESS) {
        err = g.clSetKernelArg(g.relu_kernel, 1, sizeof(cl_mem), &mem_y);
    }
    if (err == CL_SUCCESS) {
        err = g.clSetKernelArg(g.relu_kernel, 2, sizeof(cl_int), &count_arg);
    }
    if (err != CL_SUCCESS) {
        set_error(cl_error_to_string(err));
        return false;
    }

    /* One work-item per element, flattened global size (spec2.md 7.4). */
    size_t global_size = count;
    err = g.clEnqueueNDRangeKernel(g.queue, g.relu_kernel, 1, NULL,
        &global_size, NULL, 0, NULL, NULL);
    if (err != CL_SUCCESS) {
        set_error(cl_error_to_string(err));
        return false;
    }
    return true;
}

#else /* !GPUBRIDGE_HAVE_OPENCL */

/*
 * Stub implementation used when CMake did not find CL/cl.h on this build
 * machine (GPUBRIDGE_HAVE_OPENCL undefined). Every function is unreachable in
 * practice because available() always returns false, so gpubridge_selector.c will
 * never select this backend and never call init()/malloc_device/etc. on it
 * — these bodies exist only so the GpuBridgeBackend vtable below has something
 * valid to point at and the file compiles cleanly with no OpenCL headers
 * present at all.
 */

static bool opencl_available(void) { return false; }
static bool opencl_init(void) { return false; }
static void opencl_shutdown(void) {}
static void* opencl_malloc_device(size_t bytes) { (void)bytes; return NULL; }
static void opencl_free_device(void* ptr) { (void)ptr; }
static bool opencl_copy_to_device(void* dst, const void* src, size_t bytes)
{
    (void)dst; (void)src; (void)bytes;
    return false;
}
static bool opencl_copy_to_host(void* dst, const void* src, size_t bytes)
{
    (void)dst; (void)src; (void)bytes;
    return false;
}
static bool opencl_launch_vector_add_f32(
    const float* a, const float* b, float* c, size_t n)
{
    (void)a; (void)b; (void)c; (void)n;
    return false;
}
static bool opencl_sync(void) { return false; }
static const char* opencl_last_error(void)
{
    return "OpenCL support was not compiled in (CL/cl.h not found)";
}

/* Milestone 1.5 addition: unreachable in practice (same reason as every
 * other stub above), but returns an honest all-unsupported GpuBridgeBackendCaps
 * rather than leaving the vtable slot NULL. */
static bool opencl_get_caps(GpuBridgeBackendCaps* out_caps)
{
    *out_caps = (GpuBridgeBackendCaps){ 0 };
    return true;
}

/* Milestone 2 additions: same always-fails stub pattern as the functions
 * above, for the four new tensor ops — unreachable in practice since
 * available() is always false, but needed so the vtable below has valid
 * function pointers when built without OpenCL headers. */
static bool opencl_launch_matmul_f32(
    const float* a, const float* b, float* c, size_t m, size_t k, size_t n)
{
    (void)a; (void)b; (void)c; (void)m; (void)k; (void)n;
    return false;
}
static bool opencl_launch_reduce_sum_f32(
    const float* a, float* result, size_t n)
{
    (void)a; (void)result; (void)n;
    return false;
}
static bool opencl_launch_broadcast_add_f32(
    float* y, const float* bias, size_t rows, size_t cols)
{
    (void)y; (void)bias; (void)rows; (void)cols;
    return false;
}
static bool opencl_launch_relu_f32(const float* x, float* y, size_t count)
{
    (void)x; (void)y; (void)count;
    return false;
}

/* Milestone 3 addition (spec3.md section 8.5): unreachable in practice
 * (same reason as every other stub above), but writes an honest "unknown"
 * rather than leaving buf untouched. */
bool gpuBridgeOpenclGetDeviceName(char* buf, size_t buf_len)
{
    if (buf_len > 0) { buf[0] = '\0'; }
    return false;
}

/* Phase 4 addition: unreachable in practice (same reason as every other
 * stub above), but writes an honest 0 rather than leaving *out_bytes
 * untouched. */
bool gpuBridgeOpenclGetDeviceMemoryLimit(size_t* out_bytes)
{
    *out_bytes = 0;
    return false;
}

#endif /* GPUBRIDGE_HAVE_OPENCL */

/* The OpenCL backend's vtable instance — same function-pointer shape
 * whether GPUBRIDGE_HAVE_OPENCL is defined or not, since the #else branch above
 * provides same-signature stand-ins for every function. */
static const GpuBridgeBackend g_opencl_backend = {
    .name = "opencl",
    .available = opencl_available,
    .init = opencl_init,
    .shutdown = opencl_shutdown,
    .malloc_device = opencl_malloc_device,
    .free_device = opencl_free_device,
    .copy_to_device = opencl_copy_to_device,
    .copy_to_host = opencl_copy_to_host,
    .launch_vector_add_f32 = opencl_launch_vector_add_f32,
    .sync = opencl_sync,
    .last_error = opencl_last_error,
    .launch_matmul_f32 = opencl_launch_matmul_f32,
    .launch_reduce_sum_f32 = opencl_launch_reduce_sum_f32,
    .launch_broadcast_add_f32 = opencl_launch_broadcast_add_f32,
    .launch_relu_f32 = opencl_launch_relu_f32,
    .get_caps = opencl_get_caps,
};

const GpuBridgeBackend* gpuBridgeBackendOpenclGet(void)
{
    return &g_opencl_backend;
}
