#version 450
layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0) buffer BufY { float y[]; };
layout(set = 0, binding = 1) readonly buffer BufBias { float bias[]; };

layout(push_constant) uniform PushConstants {
    int rows;
    int cols;
} pc;

void main() {
    uint i = gl_GlobalInvocationID.x;
    uint j = gl_GlobalInvocationID.y;
    if (i < uint(pc.rows) && j < uint(pc.cols)) {
        y[i * uint(pc.cols) + j] += bias[j];
    }
}
