/*
 * gpubridge_backend_vulkan.c — the Vulkan compute GPU backend (Phase 4.5,
 * spec4.5.md). Proves the same thing the OpenCL backend proved in
 * Milestone 0-1: a real device enumerated, a device-resident buffer
 * allocated/copied, a kernel compiled and launched, results read back
 * correctly — originally for exactly one op, vector_add_f32 (spec4.5.md
 * section 2's "one smoke-test op first" principle; that spec's section 4
 * non-goal 3 / section 19 exit statement scoped the other four Milestone 2
 * tensor ops out, pending Phase 5 benchmark data). This file now also
 * implements those four ops (matmul_f32/reduce_sum_f32/broadcast_add_f32/
 * relu_f32) — a deliberate, user-requested deviation from that stated gate,
 * not an oversight; see CLAUDE.md's "Phase 4.5" section for the full
 * record. Each follows this file's own matmul_f32.comp/reduce_sum_f32.comp/
 * broadcast_add_f32.comp/relu_f32.comp shaders and the existing OpenCL
 * kernels' dispatch-dimension/buffer-order semantics exactly (see each
 * vulkan_launch_*_f32 function below).
 *
 * Same three design decisions as gpubridge_backend_opencl.c, applied to Vulkan
 * (spec4.5.md section 6):
 *
 * 1. NO LINK-TIME DEPENDENCY ON VULKAN. <vulkan/vulkan.h> is included for
 *    types only (with VK_NO_PROTOTYPES defined, so it contributes no extern
 *    function declarations we could accidentally call directly — see below).
 *    Every real Vulkan entry point, including vkCreateInstance itself, is
 *    resolved at runtime via dlopen("libvulkan.so.1") + vkGetInstanceProcAddr
 *    (the one guaranteed anchor symbol, dlsym'd directly). Verify with
 *    `readelf -d build/gpubridge_vecadd_test | grep NEEDED` — no libvulkan entry.
 *
 * 2. A TWO-HANDLE WRAPPER STRUCT DISGUISED AS void*. Unlike OpenCL's cl_mem
 *    (itself pointer-shaped), Vulkan needs both a VkBuffer and a backing
 *    VkDeviceMemory per allocation — neither alone is void*-castable. See
 *    GpuBridgeVulkanBuffer below (spec4.5.md section 8).
 *
 * 3. THE WHOLE REAL IMPLEMENTATION IS #ifdef GPUBRIDGE_HAVE_VULKAN. CMake only
 *    defines it when vulkan/vulkan.h was found; the #else branch is a
 *    trivial always-unavailable stub, so this file always compiles.
 *
 * One difference from OpenCL worth calling out: instead of hand-writing
 * PFN_vk* function-pointer typedefs (as gpubridge_backend_opencl.c does for
 * CL/cl.h, which provides none), this file reuses vulkan.h's own PFN_vk*
 * typedefs directly — vulkan_core.h already declares one for every command,
 * unconditionally (only the *extern function prototypes* are guarded by
 * VK_NO_PROTOTYPES, not the typedefs). Hand-duplicating them would risk
 * silently drifting from the real prototypes; reusing the header's own
 * typedefs cannot drift.
 */
#include "gpubridge_backend.h"

#ifdef GPUBRIDGE_HAVE_VULKAN

/* Removes vulkan.h's extern function prototypes (vkCreateInstance(...) etc.)
 * — we never link libvulkan, so calling one of those directly would be a
 * link error anyway, but VK_NO_PROTOTYPES turns that into an immediate
 * compile error instead if this file ever accidentally typed "vkCreateInstance("
 * instead of "g.vkCreateInstance(" — a useful safety net for a file this
 * dependent on getting every call routed through the resolved function
 * pointer table. The PFN_vk* typedefs this file reuses are unaffected. */
#define VK_NO_PROTOTYPES
#include <vulkan/vulkan.h>
#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

/* Generated by CMake at configure time from
 * backends/vulkan/vector_add_f32.spv (see CMakeLists.txt's file(READ ... HEX)
 * + configure_file() step and cmake/vector_add_f32_spv.h.in). Defines
 * `static const unsigned char kVectorAddF32Spv[]`/`kVectorAddF32SpvSize` —
 * the single source of truth is backends/vulkan/vector_add_f32.comp,
 * compiled offline via glslangValidator (spec4.5.md section 9.2). */
#include "generated/vector_add_f32_spv.h"

/* The four Milestone 2 tensor ops, ported to Vulkan beyond spec4.5.md's own
 * vector_add_f32-only scope (that spec's section 4 non-goal 3 / section 19
 * exit statement scoped them out pending Phase 5 benchmark data — this is a
 * deliberate, user-requested deviation from that stated gate, not an
 * oversight; see CLAUDE.md's "Phase 4.5" section for the full record). Same
 * embedding technique, one generated header per op. */
#include "generated/matmul_f32_spv.h"
#include "generated/reduce_sum_f32_spv.h"
#include "generated/broadcast_add_f32_spv.h"
#include "generated/relu_f32_spv.h"

/*
 * One op's complete pipeline state (section 9's "Pipeline construction"
 * list, generalized beyond vector_add_f32 to every op this backend
 * implements — see the top-of-file comment's "beyond spec4.5.md's own
 * scope" note). Each op gets its own descriptor set layout/pipeline
 * layout/shader module/pipeline/descriptor pool+set, built once in
 * vulkan_init() via build_op_pipeline() and reused across every launch of
 * that op — same reuse-is-safe-because-every-call-fence-waits reasoning
 * section 9 item 5 already established for vector_add_f32, unchanged by
 * having five of these instead of one. Declared before `g` below since `g`
 * embeds five of these directly (not pointers), so the full type must
 * already be known.
 */
typedef struct {
    VkDescriptorSetLayout descriptor_set_layout;
    VkPipelineLayout pipeline_layout;
    VkShaderModule shader_module;
    VkPipeline pipeline;
    VkDescriptorPool descriptor_pool;
    VkDescriptorSet descriptor_set;
} GpuBridgeVulkanOpPipeline;

/*
 * All of this backend's mutable state lives in one anonymous-struct global
 * `g`, zero-initialized by static storage duration (every VkHandle and
 * function pointer starts as NULL/VK_NULL_HANDLE with no explicit
 * initializer needed) — same shape as gpubridge_backend_opencl.c's `g`.
 * There is exactly one Vulkan backend instance in this process.
 */
static struct {
    void* dl_handle;
    bool probed;
    bool probe_result;

    PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr;

    /* Instance-level (section 6: resolved via vkGetInstanceProcAddr(NULL, ...)
     * for vkCreateInstance itself, then via vkGetInstanceProcAddr(g.instance,
     * ...) for everything else once a real instance exists). */
    PFN_vkCreateInstance vkCreateInstance;
    PFN_vkDestroyInstance vkDestroyInstance;
    PFN_vkEnumeratePhysicalDevices vkEnumeratePhysicalDevices;
    PFN_vkGetPhysicalDeviceQueueFamilyProperties vkGetPhysicalDeviceQueueFamilyProperties;
    PFN_vkGetPhysicalDeviceMemoryProperties vkGetPhysicalDeviceMemoryProperties;
    /* Not part of spec4.5.md's own scope, but needed so
     * gpuBridgeVulkanGetDeviceName()/gpuBridgeVulkanGetDeviceMemoryLimit()
     * below can answer gpuBridgeGetSelectedDeviceName()/
     * gpuBridgeGetDeviceMemoryLimit()/gpuBridgeGetHardwareTier()
     * (gpubridge_runtime.c, Milestone 3 / Phase 4) honestly instead of
     * silently misreporting this backend as CPU. */
    PFN_vkGetPhysicalDeviceProperties vkGetPhysicalDeviceProperties;
    PFN_vkCreateDevice vkCreateDevice;
    PFN_vkDestroyDevice vkDestroyDevice;

    /* Device-level (also resolved via vkGetInstanceProcAddr — non-goal 3:
     * no vkGetDeviceProcAddr dispatch-table optimization this phase). */
    PFN_vkGetDeviceQueue vkGetDeviceQueue;
    PFN_vkCreateBuffer vkCreateBuffer;
    PFN_vkDestroyBuffer vkDestroyBuffer;
    PFN_vkGetBufferMemoryRequirements vkGetBufferMemoryRequirements;
    PFN_vkAllocateMemory vkAllocateMemory;
    PFN_vkFreeMemory vkFreeMemory;
    PFN_vkBindBufferMemory vkBindBufferMemory;
    PFN_vkMapMemory vkMapMemory;
    PFN_vkUnmapMemory vkUnmapMemory;
    PFN_vkCreateCommandPool vkCreateCommandPool;
    PFN_vkDestroyCommandPool vkDestroyCommandPool;
    PFN_vkAllocateCommandBuffers vkAllocateCommandBuffers;
    PFN_vkFreeCommandBuffers vkFreeCommandBuffers;
    PFN_vkResetCommandBuffer vkResetCommandBuffer;
    PFN_vkBeginCommandBuffer vkBeginCommandBuffer;
    PFN_vkEndCommandBuffer vkEndCommandBuffer;
    PFN_vkCmdCopyBuffer vkCmdCopyBuffer;
    PFN_vkCmdBindPipeline vkCmdBindPipeline;
    PFN_vkCmdBindDescriptorSets vkCmdBindDescriptorSets;
    PFN_vkCmdPushConstants vkCmdPushConstants;
    PFN_vkCmdDispatch vkCmdDispatch;
    PFN_vkCreateFence vkCreateFence;
    PFN_vkDestroyFence vkDestroyFence;
    PFN_vkResetFences vkResetFences;
    PFN_vkWaitForFences vkWaitForFences;
    PFN_vkQueueSubmit vkQueueSubmit;
    PFN_vkQueueWaitIdle vkQueueWaitIdle;
    PFN_vkCreateShaderModule vkCreateShaderModule;
    PFN_vkDestroyShaderModule vkDestroyShaderModule;
    PFN_vkCreateDescriptorSetLayout vkCreateDescriptorSetLayout;
    PFN_vkDestroyDescriptorSetLayout vkDestroyDescriptorSetLayout;
    PFN_vkCreatePipelineLayout vkCreatePipelineLayout;
    PFN_vkDestroyPipelineLayout vkDestroyPipelineLayout;
    PFN_vkCreateComputePipelines vkCreateComputePipelines;
    PFN_vkDestroyPipeline vkDestroyPipeline;
    PFN_vkCreateDescriptorPool vkCreateDescriptorPool;
    PFN_vkDestroyDescriptorPool vkDestroyDescriptorPool;
    PFN_vkAllocateDescriptorSets vkAllocateDescriptorSets;
    PFN_vkUpdateDescriptorSets vkUpdateDescriptorSets;

    VkInstance instance;
    VkPhysicalDevice physical_device;
    uint32_t queue_family_index;
    VkPhysicalDeviceMemoryProperties mem_props;
    VkDevice device;
    VkQueue queue;

    /* One command pool, one command buffer, reset and re-recorded for every
     * copy_to_device/copy_to_host/launch_vector_add_f32 call (section 7's
     * "Command pool" paragraph) — matching this backend's single-threaded,
     * fully-synchronous execution model (non-goal 6). */
    VkCommandPool command_pool;
    VkCommandBuffer cmd;
    VkFence fence;

    /* Pipeline state, built once in vulkan_init() (section 9's "Pipeline
     * construction" list) and reused across every launch — one
     * GpuBridgeVulkanOpPipeline per op this backend implements (see that
     * type's own comment for why there are now five instead of the
     * original one). */
    GpuBridgeVulkanOpPipeline vector_add_pipeline;
    GpuBridgeVulkanOpPipeline matmul_pipeline;
    GpuBridgeVulkanOpPipeline reduce_sum_pipeline;
    GpuBridgeVulkanOpPipeline broadcast_add_pipeline;
    GpuBridgeVulkanOpPipeline relu_pipeline;

    char last_error[256];
} g;

/*
 * Opaque device-buffer handle (section 8). malloc_device() heap-allocates
 * one of these and returns it cast to void*; every other function here
 * casts it straight back. Never dereferenced by gpubridge_runtime.c or any
 * caller outside this file.
 */
typedef struct {
    VkBuffer buffer;
    VkDeviceMemory memory;
    VkDeviceSize size;
} GpuBridgeVulkanBuffer;

static void set_error(const char* msg)
{
    snprintf(g.last_error, sizeof(g.last_error), "%s", msg);
}

/* Idempotent: safe to call repeatedly; only actually dlopen()s once. Tries
 * the versioned SONAME (what's actually installed at runtime), same
 * precedent as gpubridge_backend_opencl.c's dl_open_loader(). */
static bool dl_open_loader(void)
{
    if (g.dl_handle != NULL) {
        return true;
    }
    g.dl_handle = dlopen("libvulkan.so.1", RTLD_NOW);
    return g.dl_handle != NULL;
}

/*
 * The minimal resolve step needed just to *probe* whether a Vulkan-capable
 * compute device exists (section 6: "resolve_probe_symbols() ... resolves
 * only vkCreateInstance, vkEnumeratePhysicalDevices, and
 * vkGetPhysicalDeviceQueueFamilyProperties"). Only vkCreateInstance can
 * actually be resolved before an instance exists (it's a global-level
 * command, fetchable via vkGetInstanceProcAddr(NULL, ...) — "the documented
 * way to fetch global-level commands", section 4); the other two are
 * instance-level and are resolved against a temporary probe instance inside
 * vulkan_available() itself, once vkCreateInstance has actually been called.
 */
static bool resolve_probe_symbols(void)
{
    if (g.vkGetInstanceProcAddr == NULL) {
        g.vkGetInstanceProcAddr =
            (PFN_vkGetInstanceProcAddr)dlsym(g.dl_handle, "vkGetInstanceProcAddr");
        if (g.vkGetInstanceProcAddr == NULL) {
            set_error("failed to resolve vkGetInstanceProcAddr from libvulkan.so.1");
            return false;
        }
    }
    g.vkCreateInstance = (PFN_vkCreateInstance)(void*)
        g.vkGetInstanceProcAddr(NULL, "vkCreateInstance");
    if (g.vkCreateInstance == NULL) {
        set_error("failed to resolve vkCreateInstance via vkGetInstanceProcAddr");
        return false;
    }
    return true;
}

static bool vulkan_available(void)
{
    /* Cache the result: available() must be cheap to call repeatedly
     * (gpubridge_selector.c calls it on every gpuBridgeInit()/gpuBridgeSetBackend()).
     * The first call does the real dlopen+probe work. */
    if (g.probed) {
        return g.probe_result;
    }
    g.probed = true;
    g.probe_result = false;

    if (!dl_open_loader()) {
        return false; /* Vulkan loader simply not installed. */
    }
    if (!resolve_probe_symbols()) {
        return false;
    }

    /* Minimal probe instance, same zero-layer/zero-extension shape
     * vulkan_init() uses for the real one (section 7) — kept as one
     * instance-creation shape, not two divergent ones. */
    VkApplicationInfo app_info = {
        .sType = VK_STRUCTURE_TYPE_APPLICATION_INFO,
        .apiVersion = VK_API_VERSION_1_0,
    };
    VkInstanceCreateInfo instance_info = {
        .sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
        .pApplicationInfo = &app_info,
    };
    VkInstance probe_instance;
    if (g.vkCreateInstance(&instance_info, NULL, &probe_instance) != VK_SUCCESS) {
        return false;
    }

    PFN_vkEnumeratePhysicalDevices enum_devices = (PFN_vkEnumeratePhysicalDevices)(void*)
        g.vkGetInstanceProcAddr(probe_instance, "vkEnumeratePhysicalDevices");
    PFN_vkGetPhysicalDeviceQueueFamilyProperties get_qfp =
        (PFN_vkGetPhysicalDeviceQueueFamilyProperties)(void*)
        g.vkGetInstanceProcAddr(probe_instance, "vkGetPhysicalDeviceQueueFamilyProperties");
    if (enum_devices == NULL || get_qfp == NULL) {
        return false;
    }

    uint32_t device_count = 0;
    enum_devices(probe_instance, &device_count, NULL);
    bool found = false;
    if (device_count > 0) {
        VkPhysicalDevice* devices = malloc(sizeof(VkPhysicalDevice) * device_count);
        if (devices != NULL) {
            enum_devices(probe_instance, &device_count, devices);
            for (uint32_t i = 0; i < device_count && !found; i++) {
                uint32_t qf_count = 0;
                get_qfp(devices[i], &qf_count, NULL);
                if (qf_count == 0) {
                    continue;
                }
                VkQueueFamilyProperties* qfs =
                    malloc(sizeof(VkQueueFamilyProperties) * qf_count);
                if (qfs == NULL) {
                    continue;
                }
                get_qfp(devices[i], &qf_count, qfs);
                for (uint32_t f = 0; f < qf_count; f++) {
                    if (qfs[f].queueFlags & VK_QUEUE_COMPUTE_BIT) {
                        found = true;
                        break;
                    }
                }
                free(qfs);
            }
            free(devices);
        }
    }

    /* Probe instance intentionally never vkDestroyInstance'd: this whole
     * function runs at most once per process (result cached above), and
     * section 6 deliberately scopes resolve_probe_symbols() to exclude
     * vkDestroyInstance — vulkan_init() below creates its own, separate,
     * properly-destroyed instance rather than reusing this one, the same
     * "re-probe rather than reuse" precedent
     * gpubridge_backend_opencl.c's opencl_init()/find_gpu_device() already
     * established for cl_platform_id/cl_device_id. A single leaked
     * VkInstance for the process lifetime is the accepted cost. */
    g.probe_result = found;
    return found;
}

/* First (device, queue family) pair anywhere with VK_QUEUE_COMPUTE_BIT set —
 * no scoring, no discrete/integrated preference (section 7, non-goal 4). */
static bool find_physical_device_and_queue_family(void)
{
    uint32_t device_count = 0;
    g.vkEnumeratePhysicalDevices(g.instance, &device_count, NULL);
    if (device_count == 0) {
        return false;
    }
    VkPhysicalDevice* devices = malloc(sizeof(VkPhysicalDevice) * device_count);
    if (devices == NULL) {
        return false;
    }
    g.vkEnumeratePhysicalDevices(g.instance, &device_count, devices);

    bool found = false;
    for (uint32_t i = 0; i < device_count && !found; i++) {
        uint32_t qf_count = 0;
        g.vkGetPhysicalDeviceQueueFamilyProperties(devices[i], &qf_count, NULL);
        if (qf_count == 0) {
            continue;
        }
        VkQueueFamilyProperties* qfs = malloc(sizeof(VkQueueFamilyProperties) * qf_count);
        if (qfs == NULL) {
            continue;
        }
        g.vkGetPhysicalDeviceQueueFamilyProperties(devices[i], &qf_count, qfs);
        for (uint32_t f = 0; f < qf_count; f++) {
            if (qfs[f].queueFlags & VK_QUEUE_COMPUTE_BIT) {
                g.physical_device = devices[i];
                g.queue_family_index = f;
                found = true;
                break;
            }
        }
        free(qfs);
    }
    free(devices);
    return found;
}

/* Iterates g.mem_props.memoryTypes, returns the index of the first type
 * whose bit is set in `type_filter` (from vkGetBufferMemoryRequirements)
 * AND whose propertyFlags contain every bit in `required_flags`. Returns
 * UINT32_MAX if none match (section 7's "Memory type lookup helper"). */
static uint32_t find_memory_type(uint32_t type_filter, VkMemoryPropertyFlags required_flags)
{
    for (uint32_t i = 0; i < g.mem_props.memoryTypeCount; i++) {
        if ((type_filter & (1u << i)) &&
            (g.mem_props.memoryTypes[i].propertyFlags & required_flags) == required_flags) {
            return i;
        }
    }
    return UINT32_MAX;
}

/* Descriptor set layout / pipeline layout / shader module / pipeline /
 * descriptor pool+set for one op — built once per op in vulkan_init()
 * (section 9's "Pipeline construction" list, generalized from a single
 * vector_add_f32-only build to `binding_count`/`push_constant_size`
 * parameters so the same function builds all five ops' pipelines). Reused
 * across every launch of that op, same as the original single-op version. */
static bool build_op_pipeline(const unsigned char* spv_code, size_t spv_size,
    uint32_t binding_count, uint32_t push_constant_size,
    GpuBridgeVulkanOpPipeline* out)
{
    VkDescriptorSetLayoutBinding bindings[3];
    for (uint32_t i = 0; i < binding_count; i++) {
        bindings[i] = (VkDescriptorSetLayoutBinding){
            .binding = i,
            .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
            .descriptorCount = 1,
            .stageFlags = VK_SHADER_STAGE_COMPUTE_BIT,
        };
    }
    VkDescriptorSetLayoutCreateInfo layout_info = {
        .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
        .bindingCount = binding_count,
        .pBindings = bindings,
    };
    if (g.vkCreateDescriptorSetLayout(g.device, &layout_info, NULL,
            &out->descriptor_set_layout) != VK_SUCCESS) {
        set_error("vkCreateDescriptorSetLayout failed");
        return false;
    }

    VkPushConstantRange push_range = {
        .stageFlags = VK_SHADER_STAGE_COMPUTE_BIT,
        .offset = 0,
        .size = push_constant_size,
    };
    VkPipelineLayoutCreateInfo pipeline_layout_info = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
        .setLayoutCount = 1,
        .pSetLayouts = &out->descriptor_set_layout,
        .pushConstantRangeCount = 1,
        .pPushConstantRanges = &push_range,
    };
    if (g.vkCreatePipelineLayout(g.device, &pipeline_layout_info, NULL,
            &out->pipeline_layout) != VK_SUCCESS) {
        set_error("vkCreatePipelineLayout failed");
        return false;
    }

    VkShaderModuleCreateInfo shader_info = {
        .sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
        .codeSize = spv_size,
        .pCode = (const uint32_t*)(const void*)spv_code,
    };
    if (g.vkCreateShaderModule(g.device, &shader_info, NULL, &out->shader_module) != VK_SUCCESS) {
        set_error("vkCreateShaderModule failed");
        return false;
    }

    VkComputePipelineCreateInfo pipeline_info = {
        .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
        .stage = {
            .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
            .stage = VK_SHADER_STAGE_COMPUTE_BIT,
            .module = out->shader_module,
            .pName = "main",
        },
        .layout = out->pipeline_layout,
    };
    if (g.vkCreateComputePipelines(g.device, VK_NULL_HANDLE, 1, &pipeline_info, NULL,
            &out->pipeline) != VK_SUCCESS) {
        set_error("vkCreateComputePipelines failed");
        return false;
    }

    VkDescriptorPoolSize pool_size = {
        .type = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
        .descriptorCount = binding_count,
    };
    VkDescriptorPoolCreateInfo descriptor_pool_info = {
        .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO,
        .maxSets = 1,
        .poolSizeCount = 1,
        .pPoolSizes = &pool_size,
    };
    if (g.vkCreateDescriptorPool(g.device, &descriptor_pool_info, NULL,
            &out->descriptor_pool) != VK_SUCCESS) {
        set_error("vkCreateDescriptorPool failed");
        return false;
    }

    VkDescriptorSetAllocateInfo set_alloc_info = {
        .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO,
        .descriptorPool = out->descriptor_pool,
        .descriptorSetCount = 1,
        .pSetLayouts = &out->descriptor_set_layout,
    };
    if (g.vkAllocateDescriptorSets(g.device, &set_alloc_info, &out->descriptor_set) != VK_SUCCESS) {
        set_error("vkAllocateDescriptorSets failed");
        return false;
    }

    return true;
}

/* Reverse-order teardown of one op's pipeline state, mirroring
 * vulkan_shutdown()'s existing "guarded by both handle-exists and
 * destroy-fn-resolved" convention. Safe to call on a zero-initialized or
 * partially-built GpuBridgeVulkanOpPipeline (e.g. if vulkan_init() failed
 * partway through building the second or later op's pipeline). */
static void destroy_op_pipeline(GpuBridgeVulkanOpPipeline* op)
{
    if (op->descriptor_pool && g.vkDestroyDescriptorPool) {
        g.vkDestroyDescriptorPool(g.device, op->descriptor_pool, NULL);
        op->descriptor_pool = VK_NULL_HANDLE;
    }
    if (op->pipeline && g.vkDestroyPipeline) {
        g.vkDestroyPipeline(g.device, op->pipeline, NULL);
        op->pipeline = VK_NULL_HANDLE;
    }
    if (op->pipeline_layout && g.vkDestroyPipelineLayout) {
        g.vkDestroyPipelineLayout(g.device, op->pipeline_layout, NULL);
        op->pipeline_layout = VK_NULL_HANDLE;
    }
    if (op->shader_module && g.vkDestroyShaderModule) {
        g.vkDestroyShaderModule(g.device, op->shader_module, NULL);
        op->shader_module = VK_NULL_HANDLE;
    }
    if (op->descriptor_set_layout && g.vkDestroyDescriptorSetLayout) {
        g.vkDestroyDescriptorSetLayout(g.device, op->descriptor_set_layout, NULL);
        op->descriptor_set_layout = VK_NULL_HANDLE;
    }
}

/* Builds all five ops' pipelines in one place, called once at the end of
 * vulkan_init(). matmul_f32's push constants are {m,k,n} (3 int32s);
 * broadcast_add_f32's are {rows,cols} (2 int32s); vector_add_f32/
 * reduce_sum_f32/relu_f32 each take a single int32 (n/n/count
 * respectively) — sizes match each .comp shader's own PushConstants block
 * exactly (section 9 / the matmul_f32.comp etc. sources). */
static bool build_all_pipelines(void)
{
    if (!build_op_pipeline(kVectorAddF32Spv, kVectorAddF32SpvSize, 3,
            (uint32_t)sizeof(int32_t), &g.vector_add_pipeline)) {
        return false;
    }
    if (!build_op_pipeline(kMatmulF32Spv, kMatmulF32SpvSize, 3,
            (uint32_t)(3 * sizeof(int32_t)), &g.matmul_pipeline)) {
        return false;
    }
    if (!build_op_pipeline(kReduceSumF32Spv, kReduceSumF32SpvSize, 2,
            (uint32_t)sizeof(int32_t), &g.reduce_sum_pipeline)) {
        return false;
    }
    if (!build_op_pipeline(kBroadcastAddF32Spv, kBroadcastAddF32SpvSize, 2,
            (uint32_t)(2 * sizeof(int32_t)), &g.broadcast_add_pipeline)) {
        return false;
    }
    if (!build_op_pipeline(kReluF32Spv, kReluF32SpvSize, 2,
            (uint32_t)sizeof(int32_t), &g.relu_pipeline)) {
        return false;
    }
    return true;
}

/* Binds `buffer_count` storage buffers to `op`'s descriptor set, records
 * push constants (if any) plus a vkCmdDispatch of
 * (group_count_x, group_count_y, 1), submits with a fence, and blocks —
 * the shared shape behind every launch_*_f32 function below, generalized
 * from vulkan_launch_vector_add_f32's original inline body (section 8/10:
 * every Vulkan operation in this backend submits then fence-waits before
 * returning). Reusing each op's one descriptor set across calls remains
 * safe for the same reason section 9 item 5 already documents: every call
 * fence-waits before returning, so there is never a second, concurrently
 * in-flight command buffer still reading a previous binding. */
static bool dispatch_op(const GpuBridgeVulkanOpPipeline* op,
    const VkBuffer* buffers, uint32_t buffer_count,
    const void* push_constants, uint32_t push_constants_size,
    uint32_t group_count_x, uint32_t group_count_y)
{
    VkDescriptorBufferInfo buffer_infos[3];
    VkWriteDescriptorSet writes[3];
    for (uint32_t i = 0; i < buffer_count; i++) {
        buffer_infos[i] = (VkDescriptorBufferInfo){
            .buffer = buffers[i], .offset = 0, .range = VK_WHOLE_SIZE,
        };
        writes[i] = (VkWriteDescriptorSet){
            .sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
            .dstSet = op->descriptor_set,
            .dstBinding = i,
            .descriptorCount = 1,
            .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
            .pBufferInfo = &buffer_infos[i],
        };
    }
    g.vkUpdateDescriptorSets(g.device, buffer_count, writes, 0, NULL);

    g.vkResetCommandBuffer(g.cmd, 0);
    VkCommandBufferBeginInfo begin_info = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO,
        .flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT,
    };
    if (g.vkBeginCommandBuffer(g.cmd, &begin_info) != VK_SUCCESS) {
        set_error("vkBeginCommandBuffer failed");
        return false;
    }
    g.vkCmdBindPipeline(g.cmd, VK_PIPELINE_BIND_POINT_COMPUTE, op->pipeline);
    g.vkCmdBindDescriptorSets(g.cmd, VK_PIPELINE_BIND_POINT_COMPUTE,
        op->pipeline_layout, 0, 1, &op->descriptor_set, 0, NULL);
    if (push_constants_size > 0) {
        g.vkCmdPushConstants(g.cmd, op->pipeline_layout, VK_SHADER_STAGE_COMPUTE_BIT,
            0, push_constants_size, push_constants);
    }
    g.vkCmdDispatch(g.cmd, group_count_x, group_count_y, 1);
    if (g.vkEndCommandBuffer(g.cmd) != VK_SUCCESS) {
        set_error("vkEndCommandBuffer failed");
        return false;
    }

    g.vkResetFences(g.device, 1, &g.fence);
    VkSubmitInfo submit_info = {
        .sType = VK_STRUCTURE_TYPE_SUBMIT_INFO,
        .commandBufferCount = 1,
        .pCommandBuffers = &g.cmd,
    };
    if (g.vkQueueSubmit(g.queue, 1, &submit_info, g.fence) != VK_SUCCESS) {
        set_error("vkQueueSubmit failed");
        return false;
    }
    if (g.vkWaitForFences(g.device, 1, &g.fence, VK_TRUE, UINT64_MAX) != VK_SUCCESS) {
        set_error("vkWaitForFences failed");
        return false;
    }
    return true;
}

static bool vulkan_init(void)
{
    if (!vulkan_available()) {
        set_error("no Vulkan-capable device with a compute queue family available");
        return false;
    }

    /* A real, long-lived instance — re-created rather than reusing
     * vulkan_available()'s probe instance (see that function's comment).
     * Same zero-layer/zero-extension, VK_API_VERSION_1_0 shape (section 7:
     * "broadest compatibility — nothing this phase needs requires 1.1+"). */
    VkApplicationInfo app_info = {
        .sType = VK_STRUCTURE_TYPE_APPLICATION_INFO,
        .apiVersion = VK_API_VERSION_1_0,
    };
    VkInstanceCreateInfo instance_info = {
        .sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
        .pApplicationInfo = &app_info,
    };
    if (g.vkCreateInstance(&instance_info, NULL, &g.instance) != VK_SUCCESS) {
        set_error("vkCreateInstance failed");
        return false;
    }

    /* Resolve every remaining command via vkGetInstanceProcAddr(g.instance,
     * ...) now that a real instance exists — instance-level and, later,
     * device-level alike (section 6 item 2; non-goal 3 explicitly forgoes
     * the vkGetDeviceProcAddr optimization). vkDestroyInstance is resolved
     * first so a later failure in this block can still tear the instance
     * down cleanly via vulkan_shutdown(). */
#define VK_RESOLVE_OR_FAIL(fn) \
    do { \
        g.fn = (PFN_##fn)(void*)g.vkGetInstanceProcAddr(g.instance, #fn); \
        if (g.fn == NULL) { \
            set_error("failed to resolve " #fn " via vkGetInstanceProcAddr"); \
            return false; \
        } \
    } while (0)

    VK_RESOLVE_OR_FAIL(vkDestroyInstance);
    VK_RESOLVE_OR_FAIL(vkEnumeratePhysicalDevices);
    VK_RESOLVE_OR_FAIL(vkGetPhysicalDeviceQueueFamilyProperties);
    VK_RESOLVE_OR_FAIL(vkGetPhysicalDeviceMemoryProperties);
    VK_RESOLVE_OR_FAIL(vkGetPhysicalDeviceProperties);
    VK_RESOLVE_OR_FAIL(vkCreateDevice);
    VK_RESOLVE_OR_FAIL(vkDestroyDevice);
    VK_RESOLVE_OR_FAIL(vkGetDeviceQueue);
    VK_RESOLVE_OR_FAIL(vkCreateBuffer);
    VK_RESOLVE_OR_FAIL(vkDestroyBuffer);
    VK_RESOLVE_OR_FAIL(vkGetBufferMemoryRequirements);
    VK_RESOLVE_OR_FAIL(vkAllocateMemory);
    VK_RESOLVE_OR_FAIL(vkFreeMemory);
    VK_RESOLVE_OR_FAIL(vkBindBufferMemory);
    VK_RESOLVE_OR_FAIL(vkMapMemory);
    VK_RESOLVE_OR_FAIL(vkUnmapMemory);
    VK_RESOLVE_OR_FAIL(vkCreateCommandPool);
    VK_RESOLVE_OR_FAIL(vkDestroyCommandPool);
    VK_RESOLVE_OR_FAIL(vkAllocateCommandBuffers);
    VK_RESOLVE_OR_FAIL(vkFreeCommandBuffers);
    VK_RESOLVE_OR_FAIL(vkResetCommandBuffer);
    VK_RESOLVE_OR_FAIL(vkBeginCommandBuffer);
    VK_RESOLVE_OR_FAIL(vkEndCommandBuffer);
    VK_RESOLVE_OR_FAIL(vkCmdCopyBuffer);
    VK_RESOLVE_OR_FAIL(vkCmdBindPipeline);
    VK_RESOLVE_OR_FAIL(vkCmdBindDescriptorSets);
    VK_RESOLVE_OR_FAIL(vkCmdPushConstants);
    VK_RESOLVE_OR_FAIL(vkCmdDispatch);
    VK_RESOLVE_OR_FAIL(vkCreateFence);
    VK_RESOLVE_OR_FAIL(vkDestroyFence);
    VK_RESOLVE_OR_FAIL(vkResetFences);
    VK_RESOLVE_OR_FAIL(vkWaitForFences);
    VK_RESOLVE_OR_FAIL(vkQueueSubmit);
    VK_RESOLVE_OR_FAIL(vkQueueWaitIdle);
    VK_RESOLVE_OR_FAIL(vkCreateShaderModule);
    VK_RESOLVE_OR_FAIL(vkDestroyShaderModule);
    VK_RESOLVE_OR_FAIL(vkCreateDescriptorSetLayout);
    VK_RESOLVE_OR_FAIL(vkDestroyDescriptorSetLayout);
    VK_RESOLVE_OR_FAIL(vkCreatePipelineLayout);
    VK_RESOLVE_OR_FAIL(vkDestroyPipelineLayout);
    VK_RESOLVE_OR_FAIL(vkCreateComputePipelines);
    VK_RESOLVE_OR_FAIL(vkDestroyPipeline);
    VK_RESOLVE_OR_FAIL(vkCreateDescriptorPool);
    VK_RESOLVE_OR_FAIL(vkDestroyDescriptorPool);
    VK_RESOLVE_OR_FAIL(vkAllocateDescriptorSets);
    VK_RESOLVE_OR_FAIL(vkUpdateDescriptorSets);
#undef VK_RESOLVE_OR_FAIL

    if (!find_physical_device_and_queue_family()) {
        set_error("no Vulkan-capable device with a compute queue family found");
        return false;
    }
    g.vkGetPhysicalDeviceMemoryProperties(g.physical_device, &g.mem_props);

    /* Logical device: one queue, the family found above, priority 1.0,
     * zero extensions, zero enabled features (section 7 — vector_add_f32
     * needs nothing beyond Vulkan 1.0 core). */
    float queue_priority = 1.0f;
    VkDeviceQueueCreateInfo queue_info = {
        .sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,
        .queueFamilyIndex = g.queue_family_index,
        .queueCount = 1,
        .pQueuePriorities = &queue_priority,
    };
    VkDeviceCreateInfo device_info = {
        .sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO,
        .queueCreateInfoCount = 1,
        .pQueueCreateInfos = &queue_info,
    };
    if (g.vkCreateDevice(g.physical_device, &device_info, NULL, &g.device) != VK_SUCCESS) {
        set_error("vkCreateDevice failed");
        return false;
    }
    g.vkGetDeviceQueue(g.device, g.queue_family_index, 0, &g.queue);

    /* One command pool (RESET_COMMAND_BUFFER_BIT: the single allocated
     * command buffer below is reset+re-recorded per call, not reallocated
     * — section 7's "Command pool" paragraph), one command buffer, one
     * fence, reused across every subsequent call. */
    VkCommandPoolCreateInfo pool_info = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO,
        .flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT,
        .queueFamilyIndex = g.queue_family_index,
    };
    if (g.vkCreateCommandPool(g.device, &pool_info, NULL, &g.command_pool) != VK_SUCCESS) {
        set_error("vkCreateCommandPool failed");
        return false;
    }

    VkCommandBufferAllocateInfo cmd_alloc_info = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,
        .commandPool = g.command_pool,
        .level = VK_COMMAND_BUFFER_LEVEL_PRIMARY,
        .commandBufferCount = 1,
    };
    if (g.vkAllocateCommandBuffers(g.device, &cmd_alloc_info, &g.cmd) != VK_SUCCESS) {
        set_error("vkAllocateCommandBuffers failed");
        return false;
    }

    VkFenceCreateInfo fence_info = { .sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO };
    if (g.vkCreateFence(g.device, &fence_info, NULL, &g.fence) != VK_SUCCESS) {
        set_error("vkCreateFence failed");
        return false;
    }

    return build_all_pipelines();
}

static void vulkan_shutdown(void)
{
    /* Every destroy call is guarded by both "was this handle ever created"
     * and "was its destroy function ever resolved" — the second guard
     * covers the edge case where vulkan_init() failed partway through the
     * VK_RESOLVE_OR_FAIL block, before every function pointer this function
     * calls was populated. Reverse order of creation, same convention as
     * opencl_shutdown(). */
    destroy_op_pipeline(&g.vector_add_pipeline);
    destroy_op_pipeline(&g.matmul_pipeline);
    destroy_op_pipeline(&g.reduce_sum_pipeline);
    destroy_op_pipeline(&g.broadcast_add_pipeline);
    destroy_op_pipeline(&g.relu_pipeline);
    if (g.fence && g.vkDestroyFence) {
        g.vkDestroyFence(g.device, g.fence, NULL);
        g.fence = VK_NULL_HANDLE;
    }
    if (g.command_pool && g.vkDestroyCommandPool) {
        g.vkDestroyCommandPool(g.device, g.command_pool, NULL);
        g.command_pool = VK_NULL_HANDLE;
    }
    if (g.device && g.vkDestroyDevice) {
        g.vkDestroyDevice(g.device, NULL);
        g.device = VK_NULL_HANDLE;
    }
    if (g.instance && g.vkDestroyInstance) {
        g.vkDestroyInstance(g.instance, NULL);
        g.instance = VK_NULL_HANDLE;
    }
}

static void* vulkan_malloc_device(size_t bytes)
{
    GpuBridgeVulkanBuffer* buf = malloc(sizeof(GpuBridgeVulkanBuffer));
    if (buf == NULL) {
        set_error("host allocation failure for GpuBridgeVulkanBuffer wrapper");
        return NULL;
    }
    buf->buffer = VK_NULL_HANDLE;
    buf->memory = VK_NULL_HANDLE;
    buf->size = (VkDeviceSize)bytes;

    /* STORAGE_BUFFER (compute shader binding) | TRANSFER_SRC | TRANSFER_DST
     * (both directions, since this buffer can be either a copy_to_device
     * destination or a copy_to_host source — section 8). */
    VkBufferCreateInfo buffer_info = {
        .sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
        .size = (VkDeviceSize)bytes,
        .usage = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT
            | VK_BUFFER_USAGE_TRANSFER_SRC_BIT
            | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
        .sharingMode = VK_SHARING_MODE_EXCLUSIVE,
    };
    if (g.vkCreateBuffer(g.device, &buffer_info, NULL, &buf->buffer) != VK_SUCCESS) {
        set_error("vkCreateBuffer failed");
        free(buf);
        return NULL;
    }

    VkMemoryRequirements mem_reqs;
    g.vkGetBufferMemoryRequirements(g.device, buf->buffer, &mem_reqs);

    /* Prefer DEVICE_LOCAL; fall back to whatever satisfies the buffer's
     * requirements at all — some integrated-GPU drivers expose only one
     * unified heap, still valid to bind (section 8). */
    uint32_t mem_type = find_memory_type(mem_reqs.memoryTypeBits,
        VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (mem_type == UINT32_MAX) {
        mem_type = find_memory_type(mem_reqs.memoryTypeBits, 0);
    }
    if (mem_type == UINT32_MAX) {
        set_error("no Vulkan memory type satisfies this buffer's requirements");
        g.vkDestroyBuffer(g.device, buf->buffer, NULL);
        free(buf);
        return NULL;
    }

    VkMemoryAllocateInfo alloc_info = {
        .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
        .allocationSize = mem_reqs.size,
        .memoryTypeIndex = mem_type,
    };
    if (g.vkAllocateMemory(g.device, &alloc_info, NULL, &buf->memory) != VK_SUCCESS) {
        set_error("vkAllocateMemory failed");
        g.vkDestroyBuffer(g.device, buf->buffer, NULL);
        free(buf);
        return NULL;
    }

    if (g.vkBindBufferMemory(g.device, buf->buffer, buf->memory, 0) != VK_SUCCESS) {
        set_error("vkBindBufferMemory failed");
        g.vkFreeMemory(g.device, buf->memory, NULL);
        g.vkDestroyBuffer(g.device, buf->buffer, NULL);
        free(buf);
        return NULL;
    }

    return (void*)buf;
}

static void vulkan_free_device(void* ptr)
{
    if (ptr == NULL) {
        return;
    }
    GpuBridgeVulkanBuffer* buf = (GpuBridgeVulkanBuffer*)ptr;
    if (buf->buffer) {
        g.vkDestroyBuffer(g.device, buf->buffer, NULL);
    }
    if (buf->memory) {
        g.vkFreeMemory(g.device, buf->memory, NULL);
    }
    free(buf);
}

/* Creates a transient staging VkBuffer with the given usage and
 * HOST_VISIBLE|HOST_COHERENT memory (section 8) — HOST_COHERENT means no
 * explicit vkFlushMappedMemoryRanges/vkInvalidateMappedMemoryRanges is
 * needed around the memcpy in vulkan_copy_to_device/vulkan_copy_to_host. */
static bool create_staging_buffer(size_t bytes, VkBufferUsageFlags usage,
    VkBuffer* out_buffer, VkDeviceMemory* out_memory)
{
    VkBufferCreateInfo buffer_info = {
        .sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
        .size = (VkDeviceSize)bytes,
        .usage = usage,
        .sharingMode = VK_SHARING_MODE_EXCLUSIVE,
    };
    if (g.vkCreateBuffer(g.device, &buffer_info, NULL, out_buffer) != VK_SUCCESS) {
        set_error("vkCreateBuffer (staging) failed");
        return false;
    }
    VkMemoryRequirements mem_reqs;
    g.vkGetBufferMemoryRequirements(g.device, *out_buffer, &mem_reqs);
    uint32_t mem_type = find_memory_type(mem_reqs.memoryTypeBits,
        VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
    if (mem_type == UINT32_MAX) {
        set_error("no host-visible+coherent Vulkan memory type available for staging");
        g.vkDestroyBuffer(g.device, *out_buffer, NULL);
        return false;
    }
    VkMemoryAllocateInfo alloc_info = {
        .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
        .allocationSize = mem_reqs.size,
        .memoryTypeIndex = mem_type,
    };
    if (g.vkAllocateMemory(g.device, &alloc_info, NULL, out_memory) != VK_SUCCESS) {
        set_error("vkAllocateMemory (staging) failed");
        g.vkDestroyBuffer(g.device, *out_buffer, NULL);
        return false;
    }
    if (g.vkBindBufferMemory(g.device, *out_buffer, *out_memory, 0) != VK_SUCCESS) {
        set_error("vkBindBufferMemory (staging) failed");
        g.vkFreeMemory(g.device, *out_memory, NULL);
        g.vkDestroyBuffer(g.device, *out_buffer, NULL);
        return false;
    }
    return true;
}

/* Resets+re-records the one shared command buffer with a single
 * vkCmdCopyBuffer(src -> dst, full `bytes` range), submits with a fence,
 * and blocks on it (section 8) — the interface's copy_to_device/
 * copy_to_host contract requires not returning until the data has landed. */
static bool submit_copy_and_wait(VkBuffer src, VkBuffer dst, VkDeviceSize bytes)
{
    g.vkResetCommandBuffer(g.cmd, 0);
    VkCommandBufferBeginInfo begin_info = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO,
        .flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT,
    };
    if (g.vkBeginCommandBuffer(g.cmd, &begin_info) != VK_SUCCESS) {
        set_error("vkBeginCommandBuffer failed");
        return false;
    }
    VkBufferCopy region = { .srcOffset = 0, .dstOffset = 0, .size = bytes };
    g.vkCmdCopyBuffer(g.cmd, src, dst, 1, &region);
    if (g.vkEndCommandBuffer(g.cmd) != VK_SUCCESS) {
        set_error("vkEndCommandBuffer failed");
        return false;
    }

    g.vkResetFences(g.device, 1, &g.fence);
    VkSubmitInfo submit_info = {
        .sType = VK_STRUCTURE_TYPE_SUBMIT_INFO,
        .commandBufferCount = 1,
        .pCommandBuffers = &g.cmd,
    };
    if (g.vkQueueSubmit(g.queue, 1, &submit_info, g.fence) != VK_SUCCESS) {
        set_error("vkQueueSubmit failed");
        return false;
    }
    if (g.vkWaitForFences(g.device, 1, &g.fence, VK_TRUE, UINT64_MAX) != VK_SUCCESS) {
        set_error("vkWaitForFences failed");
        return false;
    }
    return true;
}

static bool vulkan_copy_to_device(void* dst, const void* src, size_t bytes)
{
    /* dst is a GpuBridgeVulkanBuffer* disguised as void* by
     * vulkan_malloc_device(); src is a plain host pointer. */
    GpuBridgeVulkanBuffer* dst_buf = (GpuBridgeVulkanBuffer*)dst;

    VkBuffer staging_buffer;
    VkDeviceMemory staging_memory;
    if (!create_staging_buffer(bytes, VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
            &staging_buffer, &staging_memory)) {
        return false;
    }

    void* mapped;
    if (g.vkMapMemory(g.device, staging_memory, 0, (VkDeviceSize)bytes, 0, &mapped)
            != VK_SUCCESS) {
        set_error("vkMapMemory (staging) failed");
        g.vkFreeMemory(g.device, staging_memory, NULL);
        g.vkDestroyBuffer(g.device, staging_buffer, NULL);
        return false;
    }
    memcpy(mapped, src, bytes);
    g.vkUnmapMemory(g.device, staging_memory);

    bool ok = submit_copy_and_wait(staging_buffer, dst_buf->buffer, (VkDeviceSize)bytes);

    g.vkFreeMemory(g.device, staging_memory, NULL);
    g.vkDestroyBuffer(g.device, staging_buffer, NULL);
    return ok;
}

static bool vulkan_copy_to_host(void* dst, const void* src, size_t bytes)
{
    /* src is a GpuBridgeVulkanBuffer* disguised as const void*; dst is a
     * plain host pointer — the mirror image of vulkan_copy_to_device. */
    const GpuBridgeVulkanBuffer* src_buf = (const GpuBridgeVulkanBuffer*)src;

    VkBuffer staging_buffer;
    VkDeviceMemory staging_memory;
    if (!create_staging_buffer(bytes, VK_BUFFER_USAGE_TRANSFER_DST_BIT,
            &staging_buffer, &staging_memory)) {
        return false;
    }

    if (!submit_copy_and_wait(src_buf->buffer, staging_buffer, (VkDeviceSize)bytes)) {
        g.vkFreeMemory(g.device, staging_memory, NULL);
        g.vkDestroyBuffer(g.device, staging_buffer, NULL);
        return false;
    }

    void* mapped;
    if (g.vkMapMemory(g.device, staging_memory, 0, (VkDeviceSize)bytes, 0, &mapped)
            != VK_SUCCESS) {
        set_error("vkMapMemory (staging) failed");
        g.vkFreeMemory(g.device, staging_memory, NULL);
        g.vkDestroyBuffer(g.device, staging_buffer, NULL);
        return false;
    }
    memcpy(dst, mapped, bytes);
    g.vkUnmapMemory(g.device, staging_memory);

    g.vkFreeMemory(g.device, staging_memory, NULL);
    g.vkDestroyBuffer(g.device, staging_buffer, NULL);
    return true;
}

static bool vulkan_launch_vector_add_f32(
    const float* a, const float* b, float* c, size_t n)
{
    /* a/b/c arrive typed as (const) float* only because that's the fixed
     * GpuBridgeBackend signature — they are actually GpuBridgeVulkanBuffer*
     * disguised as pointers by vulkan_malloc_device(). Cast back before use,
     * same convention as gpubridge_backend_opencl.c's cl_mem casts. */
    const GpuBridgeVulkanBuffer* buf_a = (const GpuBridgeVulkanBuffer*)(const void*)a;
    const GpuBridgeVulkanBuffer* buf_b = (const GpuBridgeVulkanBuffer*)(const void*)b;
    const GpuBridgeVulkanBuffer* buf_c = (const GpuBridgeVulkanBuffer*)(const void*)c;
    VkBuffer buffers[3] = { buf_a->buffer, buf_b->buffer, buf_c->buffer };
    int32_t n32 = (int32_t)n;
    /* local_size_x = 256 in vector_add_f32.comp (section 9). */
    uint32_t group_count = (uint32_t)((n + 255) / 256);
    return dispatch_op(&g.vector_add_pipeline, buffers, 3, &n32, sizeof(n32),
        group_count, 1);
}

/* --- Vulkan tensor-op port (beyond spec4.5.md's own scope — see this
 * file's top-of-file comment and CLAUDE.md's "Phase 4.5" section): the four
 * Milestone 2 ops, each following vulkan_launch_vector_add_f32's cast-back-
 * to-GpuBridgeVulkanBuffer* / dispatch_op() shape, with dispatch dimensions
 * and buffer/push-constant layout matching this project's existing OpenCL
 * kernels (matmul_f32.cl/reduce_sum_f32.cl/broadcast_add_f32.cl/relu_f32.cl)
 * and this backend's own matmul_f32.comp/reduce_sum_f32.comp/
 * broadcast_add_f32.comp/relu_f32.comp exactly. */

static bool vulkan_launch_matmul_f32(
    const float* a, const float* b, float* c, size_t m, size_t k, size_t n)
{
    const GpuBridgeVulkanBuffer* buf_a = (const GpuBridgeVulkanBuffer*)(const void*)a;
    const GpuBridgeVulkanBuffer* buf_b = (const GpuBridgeVulkanBuffer*)(const void*)b;
    const GpuBridgeVulkanBuffer* buf_c = (const GpuBridgeVulkanBuffer*)(const void*)c;
    VkBuffer buffers[3] = { buf_a->buffer, buf_b->buffer, buf_c->buffer };
    struct { int32_t m; int32_t k; int32_t n; } pc = {
        (int32_t)m, (int32_t)k, (int32_t)n,
    };
    /* One work-item per output element C[row,col], local_size (16,16) in
     * matmul_f32.comp — row (dim m) on x, col (dim n) on y, matching
     * matmul_f32.cl's get_global_id(0)/get_global_id(1) indexing. */
    uint32_t group_x = (uint32_t)((m + 15) / 16);
    uint32_t group_y = (uint32_t)((n + 15) / 16);
    return dispatch_op(&g.matmul_pipeline, buffers, 3, &pc, sizeof(pc),
        group_x, group_y);
}

static bool vulkan_launch_reduce_sum_f32(const float* a, float* result, size_t n)
{
    const GpuBridgeVulkanBuffer* buf_a = (const GpuBridgeVulkanBuffer*)(const void*)a;
    const GpuBridgeVulkanBuffer* buf_result = (const GpuBridgeVulkanBuffer*)(const void*)result;
    VkBuffer buffers[2] = { buf_a->buffer, buf_result->buffer };
    int32_t n32 = (int32_t)n;
    /* Naive single-invocation sequential accumulation, matching
     * reduce_sum_f32.cl/reduce_sum_f32.comp's local_size_x = 1 — one
     * work-group, one invocation, that invocation walks the whole array. */
    return dispatch_op(&g.reduce_sum_pipeline, buffers, 2, &n32, sizeof(n32),
        1, 1);
}

static bool vulkan_launch_broadcast_add_f32(
    float* y, const float* bias, size_t rows, size_t cols)
{
    const GpuBridgeVulkanBuffer* buf_y = (const GpuBridgeVulkanBuffer*)(const void*)y;
    const GpuBridgeVulkanBuffer* buf_bias = (const GpuBridgeVulkanBuffer*)(const void*)bias;
    VkBuffer buffers[2] = { buf_y->buffer, buf_bias->buffer };
    struct { int32_t rows; int32_t cols; } pc = {
        (int32_t)rows, (int32_t)cols,
    };
    /* One work-item per output element, local_size (16,16) in
     * broadcast_add_f32.comp — matching broadcast_add_f32.cl's 2D
     * get_global_id(0)/get_global_id(1) = (rows, cols) indexing. In-place
     * on y's buffer (bound read_write via a non-readonly `buffer` block in
     * the .comp source), same Y += bias semantics as the CL kernel. */
    uint32_t group_x = (uint32_t)((rows + 15) / 16);
    uint32_t group_y = (uint32_t)((cols + 15) / 16);
    return dispatch_op(&g.broadcast_add_pipeline, buffers, 2, &pc, sizeof(pc),
        group_x, group_y);
}

static bool vulkan_launch_relu_f32(const float* x, float* y, size_t count)
{
    const GpuBridgeVulkanBuffer* buf_x = (const GpuBridgeVulkanBuffer*)(const void*)x;
    const GpuBridgeVulkanBuffer* buf_y = (const GpuBridgeVulkanBuffer*)(const void*)y;
    VkBuffer buffers[2] = { buf_x->buffer, buf_y->buffer };
    int32_t count32 = (int32_t)count;
    /* One work-item per element, local_size_x = 256 in relu_f32.comp —
     * matching relu_f32.cl's flattened 1D indexing (spec2.md 7.4: the rank
     * of the underlying tensor doesn't matter for an elementwise op). */
    uint32_t group_count = (uint32_t)((count + 255) / 256);
    return dispatch_op(&g.relu_pipeline, buffers, 2, &count32, sizeof(count32),
        group_count, 1);
}

/* Real, not a no-op, even though every call above already fence-waits
 * internally (section 10) — for interface conformance, so a future
 * optimization pass that makes any of those calls genuinely non-blocking
 * doesn't silently break sync()'s contract by leaving it a stale no-op. */
static bool vulkan_sync(void)
{
    if (g.vkQueueWaitIdle(g.queue) != VK_SUCCESS) {
        set_error("vkQueueWaitIdle failed");
        return false;
    }
    return true;
}

static const char* vulkan_last_error(void)
{
    return g.last_error;
}

/* Honest present-tense reporting of this file's current behavior, not a
 * hardware capability probe (section 12) — mirrors opencl_get_caps()'s
 * treatment. */
static bool vulkan_get_caps(GpuBridgeBackendCaps* out_caps)
{
    *out_caps = (GpuBridgeBackendCaps){
        .supports_device_local_memory = true,
        .supports_shared_memory = false,
        .supports_host_pinned_memory = false,
        .supports_async_copy = false,
        .supports_async_kernel_launch = true,
        .supports_events = false,
        .supports_profiling_timestamps = false,
        .vendor_gemm_loaded = false,
    };
    return true;
}

/* --- Device identity (analogous to gpuBridgeOpenclGetDeviceName/
 * gpuBridgeOpenclGetDeviceMemoryLimit, Milestone 3 section 8.5 / Phase 4
 * section 9.1's "no vtable slot" precedent). Not part of spec4.5.md's own
 * scope, but needed so gpuBridgeGetSelectedDeviceName()/
 * gpuBridgeGetDeviceMemoryLimit()/gpuBridgeGetHardwareTier()
 * (gpubridge_runtime.c) report this backend honestly instead of falling
 * into their pre-existing "not OpenCL -> assume CPU" else-branch, which
 * predates this backend's existence. */
bool gpuBridgeVulkanGetDeviceName(char* buf, size_t buf_len)
{
    if (g.physical_device == VK_NULL_HANDLE || g.vkGetPhysicalDeviceProperties == NULL) {
        snprintf(buf, buf_len, "unknown");
        return false;
    }
    VkPhysicalDeviceProperties props;
    g.vkGetPhysicalDeviceProperties(g.physical_device, &props);
    snprintf(buf, buf_len, "%s", props.deviceName);
    return true;
}

bool gpuBridgeVulkanGetDeviceMemoryLimit(size_t* out_bytes)
{
    *out_bytes = 0;
    if (g.physical_device == VK_NULL_HANDLE) {
        return false;
    }
    /* Sum of every DEVICE_LOCAL heap — the closest Vulkan analogue to
     * OpenCL's single CL_DEVICE_GLOBAL_MEM_SIZE value; most single-GPU
     * systems expose exactly one such heap. */
    VkDeviceSize total = 0;
    for (uint32_t i = 0; i < g.mem_props.memoryHeapCount; i++) {
        if (g.mem_props.memoryHeaps[i].flags & VK_MEMORY_HEAP_DEVICE_LOCAL_BIT) {
            total += g.mem_props.memoryHeaps[i].size;
        }
    }
    *out_bytes = (size_t)total;
    return true;
}

#else /* !GPUBRIDGE_HAVE_VULKAN */

/*
 * Stub implementation used when CMake did not find vulkan/vulkan.h on this
 * build machine (GPUBRIDGE_HAVE_VULKAN undefined). Every function is
 * unreachable in practice because available() always returns false, so
 * gpubridge_selector.c will never select this backend — these bodies exist
 * only so the GpuBridgeBackend vtable below has something valid to point
 * at, mirroring gpubridge_backend_opencl.c's #else branch exactly.
 */

static bool vulkan_available(void) { return false; }
static bool vulkan_init(void) { return false; }
static void vulkan_shutdown(void) {}
static void* vulkan_malloc_device(size_t bytes) { (void)bytes; return NULL; }
static void vulkan_free_device(void* ptr) { (void)ptr; }
static bool vulkan_copy_to_device(void* dst, const void* src, size_t bytes)
{
    (void)dst; (void)src; (void)bytes;
    return false;
}
static bool vulkan_copy_to_host(void* dst, const void* src, size_t bytes)
{
    (void)dst; (void)src; (void)bytes;
    return false;
}
static bool vulkan_launch_vector_add_f32(
    const float* a, const float* b, float* c, size_t n)
{
    (void)a; (void)b; (void)c; (void)n;
    return false;
}
static bool vulkan_sync(void) { return false; }
static const char* vulkan_last_error(void)
{
    return "Vulkan support was not compiled in (vulkan/vulkan.h not found)";
}
static bool vulkan_get_caps(GpuBridgeBackendCaps* out_caps)
{
    *out_caps = (GpuBridgeBackendCaps){ 0 };
    return true;
}
static bool vulkan_launch_matmul_f32(
    const float* a, const float* b, float* c, size_t m, size_t k, size_t n)
{
    (void)a; (void)b; (void)c; (void)m; (void)k; (void)n;
    return false;
}
static bool vulkan_launch_reduce_sum_f32(const float* a, float* result, size_t n)
{
    (void)a; (void)result; (void)n;
    return false;
}
static bool vulkan_launch_broadcast_add_f32(
    float* y, const float* bias, size_t rows, size_t cols)
{
    (void)y; (void)bias; (void)rows; (void)cols;
    return false;
}
static bool vulkan_launch_relu_f32(const float* x, float* y, size_t count)
{
    (void)x; (void)y; (void)count;
    return false;
}

/* Unreachable in practice (same reason as every other stub above), but
 * writes honest "unknown"/0 rather than leaving buf/*out_bytes untouched. */
bool gpuBridgeVulkanGetDeviceName(char* buf, size_t buf_len)
{
    if (buf_len > 0) { buf[0] = '\0'; }
    return false;
}
bool gpuBridgeVulkanGetDeviceMemoryLimit(size_t* out_bytes)
{
    *out_bytes = 0;
    return false;
}

#endif /* GPUBRIDGE_HAVE_VULKAN */

/* The Vulkan backend's vtable instance — same function-pointer shape
 * whether GPUBRIDGE_HAVE_VULKAN is defined or not, since the #else branch
 * above provides same-signature stand-ins for every function. Zero new
 * GpuBridgeBackend vtable slots (spec4.5.md section 13). */
static const GpuBridgeBackend g_vulkan_backend = {
    .name = "vulkan",
    .available = vulkan_available,
    .init = vulkan_init,
    .shutdown = vulkan_shutdown,
    .malloc_device = vulkan_malloc_device,
    .free_device = vulkan_free_device,
    .copy_to_device = vulkan_copy_to_device,
    .copy_to_host = vulkan_copy_to_host,
    .launch_vector_add_f32 = vulkan_launch_vector_add_f32,
    .sync = vulkan_sync,
    .last_error = vulkan_last_error,
    .launch_matmul_f32 = vulkan_launch_matmul_f32,
    .launch_reduce_sum_f32 = vulkan_launch_reduce_sum_f32,
    .launch_broadcast_add_f32 = vulkan_launch_broadcast_add_f32,
    .launch_relu_f32 = vulkan_launch_relu_f32,
    .get_caps = vulkan_get_caps,
};

const GpuBridgeBackend* gpuBridgeBackendVulkanGet(void)
{
    return &g_vulkan_backend;
}
